// Presentation adapter only: CAP's refs, actions, permissions and API payloads stay authoritative.
// No source demo state, synthetic metrics, provider calls, or mutation contracts live here.
const colors={ink:'var(--ink)',vio:'var(--primary)',vioD:'var(--ai)',vioS:'var(--bg-selected)',vioL:'var(--bg-hover)',org:'var(--amber)',orgD:'#c2451f',orgS:'#ffe6dd',chip:'var(--bot-bubble)',g2:'var(--text-muted)',g3:'var(--text-tertiary)'};
const modes:Record<string,[string,string,string]>={MENU:['Bot · menú',colors.chip,'var(--text-secondary)'],AI:['CAP IA',colors.vioS,colors.vioD],HUMAN_PENDING:['En espera',colors.orgS,colors.orgD],HUMAN_ACTIVE:['En atención',colors.vio,'var(--primary-contrast)'],CLOSING:['Cerrando…',colors.orgS,colors.orgD],CLOSED:['Cerrada',colors.chip,'var(--text-secondary)']};
const initials=(name:string)=>String(name||'?').split(' ').filter(Boolean).slice(0,2).map(w=>w[0]).join('').toUpperCase();
const avatar=(name:string)=>[[colors.ink,'#fff'],[colors.vioS,colors.vioD],[colors.orgS,colors.orgD]][[...String(name||'')].reduce((a,c)=>a+c.charCodeAt(0),0)%3];
const input=(ref:any)=>(e:Event)=>{ref.value=(e.target as HTMLInputElement).value;};
const statusLabel=(status:string)=>({ONLINE:'Disponible',AWAY:'En pausa',BUSY:'Ocupado',OFFLINE:'Desconectado'} as Record<string,string>)[status]||status;
const dot=(status:string)=>status==='ONLINE'?colors.vio:['AWAY','BUSY'].includes(status)?colors.org:colors.g3;
export function claudePresentation(c:Record<string,any>){
 const has=(p:string)=>c.agent.value?.permissions.includes(p);
 const name=(username:string)=>c.users.value.find((u:any)=>u.username===username)?.name||c.dashboard.value?.agents.find((u:any)=>u.username===username)?.name||username;
 const me=c.agent.value,selected=c.selected.value;
 const list=c.items.value.filter((i:any)=>c.railFilter.value==='mine'?i.assigned_to===me?.username:c.railFilter.value==='follow'?i.disposition==='FOLLOW_UP':true);
 const selectRail=(id:string)=>{c.railFilter.value=id;c.profileOpen.value=false;c.page.value=id==='closed'||id==='follow'?'archive':'inbox';c.settings.value=false;c.filter.value=({active:'all',pending:'pending',mine:'active',bot:'ai',follow:'closed',closed:'closed'} as Record<string,string>)[id];window.history.pushState(null,'',c.page.value==='archive'?'/inbox/archive':'/inbox');void c.changeFilter();};
 const rowActions:any[]=[];
 if(selected?.mode==='HUMAN_PENDING'&&has('conversation.claim'))rowActions.push({label:'Tomar conversación',icon:'Hand',primary:true,disabled:c.busy.value,onClick:()=>c.action('claim')});
 // Source-only intervention/assignment requires endpoints that CAP does not expose in these states.
 if(selected?.mode==='HUMAN_PENDING'&&has('conversation.assign'))rowActions.push({label:'Asignar',icon:'UserRoundPlus',primary:false,disabled:true,title:'Asignación manual no disponible en esta instalación'});
 if(['AI','MENU'].includes(selected?.mode)&&has('conversation.assign'))rowActions.push({label:'Intervenir',icon:'Hand',primary:true,disabled:true,title:'Intervención manual no disponible en esta instalación'});
 if(c.canTransfer.value)rowActions.push({label:'Transferir',icon:'ArrowLeftRight',primary:false,disabled:c.busy.value,onClick:c.openTransfer},{label:'Finalizar',icon:'CircleCheck',primary:true,disabled:c.busy.value,onClick:()=>{c.closeDialog.value=true;}});
 if(selected?.mode==='CLOSED'&&has('conversation.reopen'))rowActions.push({label:'Reabrir',icon:'RotateCcw',primary:true,disabled:false,title:'Ver opciones de reapertura',onClick:()=>{c.reopenDialog.value=true;}});
 const [chip,chipBg,chipFg]=modes[selected?.mode||'MENU'];
 const displayName=selected?.name||selected?.phone||'Contacto';const [avBg,avFg]=avatar(displayName);
 const assigned=selected?.assigned_to?(selected.assigned_to===me?.username?'Asignada a ti':`Asignada a ${name(selected.assigned_to)}`):'Sin asignar';
 const system=(m:any)=>m.message_type==='system'||m.sender_type==='system';
 const speaker=(m:any)=>system(m)?'system':m.direction==='inbound'?'customer':m.sender_type==='human'?'human':m.route==='AI'?'ai':'bot';
 const selectedDisposition=selected?.disposition||c.history.value.find((s:any)=>s.id===selected?.id)?.disposition;
 const dispositionLabel=(code:string)=>c.dispositions.find((d:any)=>d[0]===code)?.[1]||code||'Cerrada';
 const dayLabel=(date:string)=>{if(!date)return '—';const parsed=new Date(date.includes('Z')||date.includes('+')?date:date.replace(' ','T')+'Z');const today=new Date(),days=Math.round((new Date(today.toDateString()).getTime()-new Date(parsed.toDateString()).getTime())/86400000);return days===0?c.when(date):days===1?'Ayer':parsed.toLocaleDateString('es',{day:'numeric',month:'short'});};
 const created=selected?.last_message_at;const lastInbound=[...c.messages.value].reverse().find((m:any)=>m.direction==='inbound');
 const outside24=!lastInbound||Date.now()-Date.parse(lastInbound.created_at.replace(' ','T')+(lastInbound.created_at.includes('Z')?'':'Z'))>86400000;
 const shell={
  home:()=>selectRail('active'),profileOpen:c.profileOpen.value,toggleProfile:()=>{c.profileOpen.value=!c.profileOpen.value;},closeProfile:()=>{c.profileOpen.value=false;},connected:c.realtimeTransport.value!=='desconectado',
  me:{name:name(me?.username||''),initials:initials(name(me?.username||'')),role:({AGENT:'Asesor',ADMIN:'Administrador',SUPERADMIN:'Superadmin'} as Record<string,string>)[me?.role],load:`${c.dashboard.value?.agents.find((u:any)=>u.id===me?.id)?.active_chat_count??'—'} de ${c.dashboard.value?.agents.find((u:any)=>u.id===me?.id)?.max_active_chats??'—'} chats activos`,dot:dot(c.myStatus.value)},
  filters:[['active','Activos','MessagesSquare'],['pending','En espera','Clock3'],['mine','Míos','UserRound'],['bot','IA y bot','Bot'],['follow','Seguimiento','CalendarClock'],['closed','Cerradas','Archive']].filter(([id])=>id!=='bot'||has('conversation.view_all')).map(([id,label,icon])=>({id,label,icon,accessibleLabel:id==='active'?'Conversaciones':id==='closed'?'Archivo':label,active:['inbox','archive'].includes(c.page.value)&&c.railFilter.value===id,badge:id==='pending'?c.items.value.filter((i:any)=>i.mode==='HUMAN_PENDING').length:id==='active'||id==='mine'?c.items.value.filter((i:any)=>['HUMAN_ACTIVE','HUMAN_PENDING','CLOSING'].includes(i.mode)&&(id!=='mine'||i.assigned_to===me?.username)).reduce((n:number,i:any)=>n+i.unread_count,0):0,onClick:()=>selectRail(id)})),
  pages:[['metrics','Métricas','ChartNoAxesCombined','metrics.view_all'],['menu','Menú del bot','ListTree','settings.manage'],['team','Equipo y permisos','ShieldCheck','users.manage'],['settings','Configuración','Settings2','settings.manage'],['diagnostics','Diagnóstico','Activity','diagnostics.view']].filter(([, , ,p])=>has(p)).map(([id,label,icon])=>({id,label,icon,active:id==='menu'?c.page.value==='settings'&&c.settingsSection.value==='bot':c.page.value===id&&(id!=='settings'||c.settingsSection.value!=='bot'),badge:id==='diagnostics'?c.incidentCount.value:0,onClick:()=>c.navigate(id==='menu'?'settings':id,id==='menu'?'bot':id==='settings'?'routing':undefined)})),
  statuses:[['ONLINE','Disponible'],['AWAY','En pausa'],['OFFLINE','Desconectado']].map(([id,label])=>({id,label,accessibleLabel:id==='AWAY'?'Ausente':label,dot:dot(id),active:c.myStatus.value===id,onClick:()=>c.setMyStatus(id)})),
  roles:[['AGENT','Asesor'],['ADMIN','Administrador'],['SUPERADMIN','Superadmin']].map(([id,label])=>({id,label,current:id===me?.role})),
  secondary:[...c.availableNav.value.filter((n:any)=>['dashboard','contacts','campaigns'].includes(n.id)).map((n:any)=>({label:n.label,onClick:()=>c.navigate(n.id)})),{label:c.theme.value==='dark'?'Modo claro':'Modo oscuro',onClick:c.toggleTheme},{label:'Ocupado',onClick:()=>c.setMyStatus('BUSY')},...(has('settings.manage')||has('audit.view')?[{label:'Herramientas avanzadas',onClick:()=>c.navigate('settings','advanced')}]:[]),...(has('settings.manage')?[{label:'Preferencias',onClick:()=>c.navigate('settings','general')}]:[]),{label:'Cerrar sesión',onClick:c.logout}]
 };
 const inbox={
  search:c.search.value,onSearch:(e:Event)=>{input(c.search)(e);c.scheduleSearch();},listCaption:`${({active:'Activos',pending:'En espera',mine:'Míos',bot:'IA y bot',follow:'Seguimiento',closed:'Cerradas'} as Record<string,string>)[c.page.value==='archive'&&c.railFilter.value!=='follow'?'closed':c.railFilter.value]} · ${list.length}`,emptyText:c.search.value?'Sin resultados para esta búsqueda.':'No hay conversaciones en esta vista.',
  items:list.map((it:any)=>{const [label,bg,fg]=modes[it.mode];const nm=it.name||it.phone||'Contacto';const av=avatar(nm);return {...it,name:nm,initials:initials(nm),avBg:av[0],avFg:av[1],selected:it.id===selected?.id,time:c.when(it.last_message_at),preview:c.preview(it),chip:label,chipBg:bg,chipFg:fg,sub:it.mode==='HUMAN_PENDING'?'Esperando asesor':it.mode==='CLOSED'?dispositionLabel(it.disposition):it.assigned_to===me?.username?'Asignada a ti':name(it.assigned_to||''),subFg:it.mode==='HUMAN_PENDING'?colors.orgD:colors.g2,onClick:()=>{c.accordion.value='contact';c.detailsOpen.value=c.viewport.value>=1320;void c.choose(it).then(()=>{c.detailsOpen.value=c.viewport.value>=1320;});}};}),
  hasMore:!!c.nextCursor.value,loadMore:()=>c.loadList(true),connected:shell.connected,
  secondaryFilters:[['active','En atención'],['unread','No leídos']].map(([id,label])=>({id,label,onClick:()=>{c.filter.value=id;c.railFilter.value='active';c.page.value='inbox';c.settings.value=false;void c.changeFilter();}})),
  sel:selected?{name:displayName,phone:selected.phone||'—',assigned,chip,chipBg,chipFg,initials:initials(displayName),avBg,avFg,window:outside24?'Fuera de ventana 24 h':'Dentro de ventana 24 h',providerId:selected.provider_contact_id}:null,
  actions:rowActions,detailsOpen:c.detailsOpen.value,toggleDetails:()=>{c.detailsOpen.value=!c.detailsOpen.value;},messageRef:(el:any)=>{c.chatScroll.value=el;},onScroll:c.onChatScroll,hasOlder:c.hasOlder.value,olderBusy:c.olderBusy.value,loadOlder:c.loadOlder,
  messages:c.messages.value.map((m:any,i:number)=>{const by=speaker(m),first=i===0||speaker(c.messages.value[i-1])!==by,last=i===c.messages.value.length-1||speaker(c.messages.value[i+1])!==by;const humanName=name(selected?.assigned_to||me?.username||'Asesor');return {id:m.id,raw:m,system:system(m),inbound:by==='customer',text:c.displayMessageText(m),time:c.when(m.provider_timestamp||m.created_at),label:({customer:displayName,human:humanName,ai:'CAP IA',bot:'Bot · menú'} as Record<string,string>)[by],labelVisible:first,avatarVisible:last,gap:last?'14px':'6px',bg:({customer:colors.vioL,human:colors.vio,ai:colors.vioS,bot:colors.chip} as Record<string,string>)[by],fg:by==='human'?'#fff':'var(--text-primary)',labelFg:by==='human'?'rgba(255,255,255,.9)':by==='bot'?'var(--text-secondary)':colors.vioD,metaFg:by==='human'?'rgba(255,255,255,.85)':colors.g2,avBg:by==='customer'?avBg:by==='human'?colors.ink:by==='ai'?colors.vio:colors.chip,avFg:by==='customer'?avFg:by==='human'||by==='ai'?'#fff':'var(--text-secondary)',initials:by==='customer'?initials(displayName):by==='human'?initials(humanName):by==='ai'?'IA':'Bot',status:m.delivery_status?`${m.delivery_status==='sent'?'✓ ':''}${c.deliveryLabel(m.delivery_status)}`:'',trace:has('audit.view')&&m.correlation_id?()=>c.showTrace(m.id):null};}),
  banner:selected?.mode==='CLOSED'?{title:'Conversación finalizada',text:`${dispositionLabel(selectedDisposition)} · ${name(selected.assigned_to||'Sin asignar')} · ${dayLabel(selected.closed_at||selected.last_message_at)}`} :null,
  newMessages:c.newMessages.value,scrollBottom:()=>{c.chatScroll.value?.scrollTo({top:c.chatScroll.value.scrollHeight,behavior:'smooth'});c.newMessages.value=false;},canSend:c.canSend.value,
  quick:(c.menu.value?.quickReplies||[]).map((text:string)=>({text,onClick:()=>{c.draft.value=text;}})),draft:c.draft.value,onDraft:input(c.draft),onFile:(e:Event)=>{c.file.value=(e.target as HTMLInputElement).files?.[0]||null;},fileName:c.file.value?.name,send:c.send,sendDisabled:c.busy.value||(!c.draft.value.trim()&&!c.file.value),busy:c.busy.value,
  lockedText:({HUMAN_PENDING:'Toma la conversación para responder. El cliente ya sabe que un asesor lo atenderá.',CLOSING:'Enviando la despedida… se archivará cuando WhatsApp confirme la entrega.',CLOSED:'Conversación archivada. Reabrirla no está disponible en esta instalación.',AI:'CAP IA está atendiendo. Puedes intervenir si necesitas tomar el control.',MENU:'El cliente está navegando el menú automático.'} as Record<string,string>)[selected?.mode]||'Este chat está asignado a otro asesor.',
  accordion:c.accordion.value,onAccordion:(id:string,e:Event)=>{const open=(e.target as HTMLDetailsElement).open;if(open)c.accordion.value=id;else if(c.accordion.value===id)c.accordion.value='';},
  contactRows:[['Teléfono',selected?.phone||'—'],['Estado',chip],['Asignación',assigned],['Intención',({product_information:'Productos',quotation:'Cotización',general:'Consulta general',human:'Pidió asesor'} as Record<string,string>)[selected?.intent]||selected?.intent||'—'],['Última actividad',c.when(created)]],returnToBot:c.canTransfer.value?()=>c.action('return-to-bot'):null,
  tags:c.conversationTags.value,tagSuggestions:c.canSend.value?c.tagOptions.value.filter((t:any)=>!c.conversationTags.value.some((old:any)=>old.id===t.id)).map((t:any)=>({...t,onClick:()=>{c.tagToAdd.value=t.id;void c.addTag();}})):[],notes:c.notes.value.map((n:any)=>({...n,date:new Date(n.created_at).toLocaleDateString('es')})),noteDraft:c.noteDraft.value,onNote:input(c.noteDraft),addNote:c.addNote,
  sessions:c.history.value.map((h:any)=>({id:h.id,current:h.id===selected?.id,initials:initials(name(h.assigned_to||'Sin asignar')),title:h.id===selected?.id?'Sesión actual':new Date(h.created_at).toLocaleDateString('es',{day:'numeric',month:'short',year:'numeric'}),agent:name(h.assigned_to||'Sin asignar'),chip:h.id===selected?.id?chip:dispositionLabel(h.disposition),onClick:()=>c.openHistory(h.id)}))
 };
 for(const it of inbox.items){it.time=dayLabel(it.last_message_at);it.unread=it.unread_count;}
 if(['active','unread'].includes(c.filter.value)&&c.railFilter.value==='active')inbox.listCaption=`${c.filter.value==='unread'?'No leídos':'En atención'} · ${inbox.items.length}`;
 inbox.contactRows[4][1]=dayLabel(created);
 for(const m of inbox.messages){
  if(m.raw.sender_type==='human'){const sender=typeof m.raw.sender_name==='string'&&m.raw.sender_name.trim()?m.raw.sender_name:'Asesor';m.label=sender;m.initials=initials(sender);}
  if(c.theme.value==='dark'&&m.raw.sender_type==='human'){m.fg='var(--primary-contrast)';m.labelFg='var(--primary-contrast)';m.metaFg='var(--primary-contrast)';}
  (m as any).retry=c.canSend.value&&c.failedMessage.value?.id===m.id?c.retryFailed:null;
 }
 const currentSession=c.history.value[0];
 for(const session of inbox.sessions){const raw=c.history.value.find((h:any)=>h.id===session.id);session.title=session.id===currentSession?.id?'Sesión actual':new Date(raw.created_at).toLocaleDateString('es',{day:'numeric',month:'short',year:'numeric'});session.chip=session.id===currentSession?.id?modes[raw.mode]?.[0]||'Sesión':dispositionLabel(raw.disposition);}
 if(selected&&currentSession&&selected.id!==currentSession.id){
  const previous=c.history.value.find((h:any)=>h.id===selected.id);
  inbox.actions=[];
  inbox.banner={title:`Sesión del ${new Date(previous?.created_at||selected.created_at).toLocaleDateString('es',{day:'numeric',month:'long'})}`,text:`${dispositionLabel(previous?.disposition)} · atendida por ${name(previous?.assigned_to||'Asesor')}`} as any;
  (inbox.banner as any).actionLabel='Volver a la sesión actual';(inbox.banner as any).onClick=()=>c.openHistory(currentSession.id);
  inbox.lockedText='Estás viendo una sesión anterior (solo lectura).';
 }
 return {shell,inbox,selectRail,statusLabel,dot,initials,avatar,dispositionLabel};
}
