const roleLabels:Record<string,string>={AGENT:'Asesor',ADMIN:'Administrador',SUPERADMIN:'Superadmin'};
const OWN=['conversation.view_own','conversation.reply_own','conversation.claim','conversation.transfer_own','conversation.close_own','metrics.view_own'];
const TEAM=['conversation.view_all','conversation.reply_all','conversation.transfer_all','conversation.close_all','conversation.reopen','conversation.assign','metrics.view_all','diagnostics.view','campaigns.view','campaigns.create','campaigns.manage'];
const groups=[
 ['Conversaciones',[['conversation.view_own','Ver sus chats y la cola','Chats asignados o en espera sin asignar'],['conversation.view_all','Ver todas las conversaciones','Chats de otros asesores, CAP IA y bot'],['conversation.claim','Tomar chats en espera',''],['conversation.reply_own','Responder sus chats',''],['conversation.reply_all','Responder cualquier chat',''],['conversation.transfer_own','Transferir sus chats','A un asesor, la cola, CAP IA o el menú'],['conversation.transfer_all','Transferir cualquier chat',''],['conversation.assign','Asignar e intervenir',''],['conversation.close_own','Finalizar sus chats',''],['conversation.close_all','Finalizar cualquier chat','Incluye forzar cierre auditado'],['conversation.reopen','Reabrir conversaciones','Crea una sesión nueva desde el historial']]],
 ['Métricas',[['metrics.view_own','Ver sus métricas',''],['metrics.view_all','Ver métricas globales','Todos los asesores y resultados']]],
 ['Campañas',[['campaigns.view','Ver campañas',''],['campaigns.create','Crear campañas',''],['campaigns.manage','Administrar campañas','']]],
 ['Administración',[['users.manage','Gestionar usuarios','Altas, capacidad y desactivación'],['roles.manage','Editar roles y permisos',''],['settings.manage','Configurar bot, IA y enrutamiento',''],['diagnostics.view','Ver diagnóstico',''],['diagnostics.retry','Resolver incidencias',''],['audit.view','Ver trazabilidad técnica','']]]
] as const;
const formatTime=(s:number|null|undefined)=>s===null||s===undefined?'—':s<60?`${s.toLocaleString('es')} s`:`${Math.floor(s/60)} min${s%60?` ${Math.round(s%60)} s`:''}`;
const inp=(ref:any)=>(e:Event)=>{ref.value=(e.target as HTMLInputElement).value;};
export function claudePages(c:Record<string,any>,visual:Record<string,any>){
 const has=(p:string)=>c.agent.value?.permissions.includes(p),d=c.dashboard.value;
 const people=(d?.agents||[]).map((a:any)=>{const user=c.users.value.find((u:any)=>u.id===a.id);return {...a,name:a.name||user?.name||a.username,role:user?.role};});
 const value=(key:string)=>d?.global[key]??0;
 const roles=['AGENT','ADMIN','SUPERADMIN'];
 const permissionCount=(role:string)=>role==='SUPERADMIN'?groups.reduce((n,[,rows])=>n+rows.length,0):role==='ADMIN'?new Set([...OWN,...TEAM]).size:OWN.length;
 const maximum=Math.max(1,...['sales','consultations','quotes','followups'].map(value));
 const metrics={dashboard:d,loading:c.dashboardLoading.value,error:c.dashboardError.value,retry:c.loadDashboard,
  ranges:[['today','Hoy'],['yesterday','Ayer'],['7','7 días'],['30','30 días']].map(([id,label])=>({id,label,selected:id===c.metricsRange.value,onClick:()=>{c.metricsRange.value=id;void c.loadDashboard();}})),
  agentFilters:[{id:'',label:'Todo el equipo'},...people.map((a:any)=>({id:a.id,label:a.name.split(' ')[0]}))].map((a:any)=>({...a,selected:a.id===c.metricsAgentId.value,onClick:()=>{c.metricsAgentId.value=a.id;void c.loadDashboard();}})),
  kpis:[{label:'Conversaciones',value:value('conversations'),sub:`${value('transfers')} transferencias`,tone:''},{label:'Mensajes',value:value('inbound')+value('outbound'),sub:`${value('inbound')} recibidos · ${value('outbound')} enviados`,tone:''},{label:c.metricsAgentId.value?'Chats finalizados':'Resueltas sin asesor',value:c.metricsAgentId.value?value('closed'):'—',sub:c.metricsAgentId.value?'con tipificación':'CAP IA + menú, sin handoff',tone:c.metricsAgentId.value?'':'violet'},{label:'1ª respuesta humana',value:formatTime(d?.timings.firstHumanResponse.p50),sub:`P50 · P95 ${formatTime(d?.timings.firstHumanResponse.p95)}`,tone:''},{label:'Ventas',value:value('sales'),sub:d?.global.salesRevenue==null?'—':`$ ${value('salesRevenue').toLocaleString('es')}`,tone:'ink'}],
  barCaption:['today','yesterday'].includes(c.metricsRange.value)?'Mensajes por hora':'Mensajes por día',bars:[],
  split:[{label:'CAP IA',value:null,color:'var(--primary)'},{label:'Menú / bot',value:null,color:'#c9caf5'},{label:'Asesores',value:null,color:'var(--amber)'}],
  slaCritical:d?.sla.criticalPending>0,slaText:d?.sla.criticalPending?`${d.sla.criticalPending} chat${d.sla.criticalPending>1?'s':''} en espera supera${d.sla.criticalPending>1?'n':''} el SLA de ${d.sla.criticalSeconds} s ahora mismo`:`Ningún chat supera el SLA de ${d?.sla.criticalSeconds??'—'} s ahora mismo`,
  dispositions:[['Venta completada','sales'],['Consulta atendida','consultations'],['Cotización enviada','quotes'],['Requiere seguimiento','followups'],['Cliente dejó de responder','noResponse'],['No se concretó venta','noSale'],['Cierre general','generalClose']].map(([label,key])=>({label,value:d?.global[key]??'—',width:d?.global[key]!=null?`${value(key)/maximum*100}%`:'0%'})).sort((a,b)=>typeof b.value==='number'&&typeof a.value==='number'?b.value-a.value:typeof a.value==='number'?-1:typeof b.value==='number'?1:0).map((r,i)=>({...r,color:i===0?'var(--primary)':i<3?'#a7a8f3':'#cfd0f8'})),
  timings:[['Espera en cola','wait'],['Primera respuesta humana','firstHumanResponse'],['Duración de atención','handling'],['Respuesta de CAP IA','aiLatencySeconds']].map(([label,key])=>({label,p50:formatTime(d?.timings[key]?.p50),p95:formatTime(d?.timings[key]?.p95)})),
  agents:people.map((a:any)=>({...a,initials:visual.initials(a.name),role:roleLabels[a.role]||'—',status:visual.statusLabel(a.status),dot:visual.dot(a.status),load:`${a.active_chat_count}/${a.max_active_chats}`,loadWidth:`${Math.min(100,a.active_chat_count/a.max_active_chats*100)}%`,loadColor:a.active_chat_count>=a.max_active_chats?'var(--amber)':'var(--primary)',incoming:a.transfersIn,outgoing:a.transfersOut,selected:a.id===c.metricsAgentId.value}))
 };
 const team={canUsers:has('users.manage'),newUser:()=>{c.newUserDialog.value=true;},search:c.teamSearch.value,onSearch:inp(c.teamSearch),
  rows:c.users.value.filter((u:any)=>[u.name,u.username].some(v=>String(v||'').toLowerCase().includes(c.teamSearch.value.toLowerCase()))).map((u:any)=>({...u,name:(u.name||u.username)+(u.id===c.agent.value?.id?' (tú)':''),initials:visual.initials(u.name||u.username),roleLabel:roleLabels[u.role],roleBg:u.role==='SUPERADMIN'?'var(--ink)':u.role==='ADMIN'?'var(--primary)':'var(--bg-selected)',roleFg:u.role==='AGENT'?'var(--ai)':'#fff',statusLabel:u.active?visual.statusLabel(u.status):'Inactivo',dot:visual.dot(u.active?u.status:'OFFLINE'),load:`${u.active_chat_count}/${u.max_active_chats}`,loadWidth:`${Math.min(100,u.active_chat_count/u.max_active_chats*100)}%`,loadColor:u.active_chat_count>=u.max_active_chats?'var(--amber)':'var(--primary)',canDecrease:has('users.manage')&&!c.capacityBusy.value&&u.max_active_chats>Math.max(1,u.active_chat_count),canIncrease:has('users.manage')&&!c.capacityBusy.value&&u.max_active_chats<100,decrease:()=>c.changeUserCapacity(u,-1),increase:()=>c.changeUserCapacity(u,1),onClick:()=>{c.selectedUser.value=u;}})),
  roles:roles.map(role=>({role,label:roleLabels[role],count:c.users.value.filter((u:any)=>u.active&&u.role===role).length,permissions:permissionCount(role)})),
  groups:groups.map(([title,rows])=>({title,rows:rows.map(([id,label,desc])=>({id,label,desc,roles:roles.map(role=>({role,checked:role==='SUPERADMIN'||(role==='ADMIN'?[...OWN,...TEAM]:OWN).includes(id)}))}))}))
 };
 const diagnostics={copy:c.copyDiagnostic,audit:has('audit.view'),canResolve:has('diagnostics.retry'),
  services:[['backend','Backend'],['database','Base de datos'],['worker','Worker'],['messagesync','MessageSync'],['messagesyncWebhook','Webhook'],['n8nTransport','n8n (transporte)'],['aiEngine','CAP IA'],['tunnel','Túnel']].map(([id,label])=>({id,label,value:c.health.value[id]||'—',degraded:!!c.health.value[id]&&!['online','reachable','healthy','stale'].includes(c.health.value[id])})),
  incidents:c.incidents.value.map((i:any)=>({...i,time:c.when(i.last_seen_at),resolve:()=>c.resolveIncident(i.id)}))
 };
 const toggle=(label:string,help:string,value:boolean|null=null)=>({label,help,value});
 const number=(label:string,help:string,value:string|null=null)=>({label,help,value});
 const section=c.settingsSection.value;
 const settings={section,tabs:[['routing','Enrutamiento y SLA'],['ai','CAP IA'],['dispositions','Tipificaciones'],['whatsapp','Canal WhatsApp']].map(([id,label])=>({id,label,selected:section===id,onClick:()=>c.navigate('settings',id)})),
  toggles:section==='ai'?[toggle('CAP IA activa','Apagada: el texto libre recibe «Falla temporal» y se ofrece un asesor.'),toggle('Bloquear falsas transferencias','Intercepta respuestas de la IA que prometen un asesor sin confirmación real.'),toggle('Ofrecer asesor si la IA falla','Añade la opción de hablar con un asesor al mensaje de error.')]:[toggle('Asignación automática','Asigna los chats en espera al asesor disponible con menos carga. Apagado: los asesores los toman manualmente.'),toggle('Asignar al instante al pedir asesor','Si el cliente elige la opción de asesor y hay capacidad, se asigna aunque la asignación automática esté apagada.'),toggle('Reasignar al desconectarse','Los chats de un asesor desconectado vuelven a la cola tras el periodo de gracia. Nunca regresan solos a la IA.')],
  numbers:section==='ai'?[number('Agrupar mensajes seguidos','Une ráfagas de texto en una sola llamada.'),number('Límite de llamadas por contacto','Por minuto; al superarlo se envía «Muchos mensajes seguidos».'),number('Pausar IA tras fallos','Fallos consecutivos antes del circuit breaker.'),number('Tiempo máximo de respuesta','Después se envía el mensaje de falla.')]:[number('Alerta de espera (SLA)','Marca en naranja los chats que esperan más que esto.',d?.sla.criticalSeconds==null?null:`${d.sla.criticalSeconds} s`),number('Periodo de gracia por desconexión','Tiempo antes de devolver chats a la cola.'),number('Espera entre solicitudes de asesor','Evita que el cliente repita «asesor» en bucle.'),number('Capacidad por defecto','Chats simultáneos para usuarios nuevos.')],
  dispositions:c.dispositions.map(([id,label]:string[])=>({id,label,amount:id==='SALE_COMPLETED',follow:id==='FOLLOW_UP'})),
  waCards:[{label:'MessageSync',value:c.health.value.messagesync==='online'?'En línea':c.health.value.messagesync||'—',icon:'PlugZap'},{label:'Webhook',value:c.health.value.messagesyncWebhook==='online'?'Registrado · propio de CAP':c.health.value.messagesyncWebhook||'—',icon:'Webhook'},{label:'Túnel público',value:c.health.value.tunnel==='online'?'Túnel público activo':c.health.value.tunnel||'—',icon:'Globe'},{label:'Último evento',value:'—',icon:'Activity'}],
  waToggles:[toggle('Convertir audios a MP3','Los audios Ogg/Opus se reproducen en cualquier navegador.'),toggle('Generar miniaturas de imagen y video','Carga la bandeja más rápido.')],testConnection:c.loadHealth
 };
 const menu=c.menu.value;
 const intents=[['product_information','Productos'],['quotation','Cotización'],['general','Consulta general']];
 const sys=[['claim','Saludo al tomar el chat','Se envía cuando un asesor toma o reabre la conversación.'],['noAgent','Sin asesores disponibles','El cliente pidió asesor y nadie tiene capacidad: continúa CAP IA.'],['returnToBot','Devolver al menú','Encabezado; las opciones se añaden solas.'],['close','Despedida al finalizar','Se envía antes de archivar y exige confirmación de entrega.'],['invalid','Opción no reconocida','Encabezado; las opciones se añaden solas.'],['aiFailure','Falla temporal de la IA','Ofrece reintentar o pasar a un asesor.'],['aiFlood','Muchos mensajes seguidos','Protege el límite de llamadas por contacto.'],['image','Imagen recibida','Solo en modo automático; no se envía a la IA.'],['audio','Audio recibido','Solo en modo automático.'],['video','Video recibido','Solo en modo automático.']];
 const welcomeParts=menu?.welcome.match(/^([\s\S]*?)\n\n([1-9](?:\uFE0F)?(?:\u20E3)?[\s\S]*?)\n\n([\s\S]*)$/);
 sys.splice(2,0,['toAI','Transferencia a CAP IA','Cuando un asesor pasa el chat a la IA.']);
 const bot={canEdit:has('settings.manage'),dirty:!!c.menuSnapshot.value&&JSON.stringify(menu)!==c.menuSnapshot.value,welcome:menu?.welcome||'',header:welcomeParts?.[1]||menu?.welcome||'',footer:welcomeParts?.[3]||'—',canEditFooter:!!welcomeParts,
  onWelcome:menu?(e:Event)=>{const value=(e.target as HTMLTextAreaElement).value;menu.welcome=welcomeParts?`${value}\n\n${welcomeParts[2]}\n\n${welcomeParts[3]}`:value;}:undefined,
  onFooter:welcomeParts?(e:Event)=>{menu.welcome=`${welcomeParts[1]}\n\n${welcomeParts[2]}\n\n${(e.target as HTMLTextAreaElement).value}`;}:undefined,
  save:c.saveMenu,discard:()=>{if(c.menuSnapshot.value)c.menu.value=JSON.parse(c.menuSnapshot.value);},
  options:Object.entries(menu?.options||{}).map(([id,raw])=>{const o=raw as any;const human=/human/i.test(o.intent),ai=!human&&intents.some(([key])=>key===o.intent);return {id,label:human?'Hablar con un asesor':intents.find(([key])=>key===o.intent)?.[1]||o.intent,reply:o.reply,onReply:(e:Event)=>{o.reply=(e.target as HTMLTextAreaElement).value;},actions:[['CAP IA','Bot',ai],['Asesor humano','UserRound',human],['Respuesta fija','MessageSquareText',!ai&&!human]].map(([label,icon,selected])=>({label,icon,selected})),isAI:ai,intents:intents.map(([key,label])=>({id:key,label,selected:o.intent===key})),hint:ai?'Responde al instante y el siguiente texto libre del cliente va a CAP IA con esta intención.':human?'Comprueba asesores disponibles. Si hay capacidad asigna al de menor carga; si no, envía «Sin asesores» y sigue CAP IA.':'Solo responde este texto. El cliente sigue en el menú (no consume IA).'};}),
  keywords:[{label:'Volver al menú',help:'El cliente regresa al menú desde modo automático.'},{label:'Pedir asesor',help:'Dispara la misma lógica que la opción de asesor.'}],
  system:sys.map(([id,label,help])=>({id,label,help,text:menu?.[id]||'',editable:id!=='toAI',onInput:id==='toAI'?undefined:(e:Event)=>{menu[id]=(e.target as HTMLTextAreaElement).value;}})),quick:(menu?.quickReplies||[]).map((text:string,id:number)=>({id,text,onInput:(e:Event)=>{menu.quickReplies[id]=(e.target as HTMLInputElement).value;}}))
 };
 const lastInbound=visual.inbox.messages.filter((m:any)=>m.inbound).at(-1)?.raw;
 for(const row of team.rows){(row as any).onDetail=row.onClick;row.onClick=()=>{if(row.active&&row.id!==c.agent.value?.id){c.deactivateTarget.value='QUEUE';c.deactivationUser.value=c.users.value.find((u:any)=>u.id===row.id);}else c.selectedUser.value=c.users.value.find((u:any)=>u.id===row.id);};}
 const outside24=!lastInbound||Date.now()-Date.parse(lastInbound.created_at)>86400000;
 const modals={kind:c.closeDialog.value?'close':c.transferDialog.value?'transfer':c.newUserDialog.value?'newUser':c.reopenDialog.value?'reopen':c.deactivationUser.value?'deact':null,name:c.selected.value?.name||c.selected.value?.phone||'',close:()=>{c.closeDialog.value=false;c.closeError.value=false;c.transferDialog.value=false;c.newUserDialog.value=false;c.reopenDialog.value=false;c.deactivationUser.value=null;},busy:c.busy.value,
  deName:c.deactivationUser.value?.name||c.deactivationUser.value?.username,deCount:c.deactivationUser.value?.active_chat_count??0,deTarget:c.deactivateTarget.value,deTargets:[{id:'QUEUE',label:'Cola general'},...c.users.value.filter((u:any)=>u.id!==c.deactivationUser.value?.id&&u.active&&u.status==='ONLINE').map((u:any)=>({id:u.id,label:`${u.name||u.username} · ${u.active_chat_count}/${u.max_active_chats}`}))],selectDeTarget:(id:string)=>{c.deactivateTarget.value=id;},deactivate:()=>c.deactivationUser.value&&c.deactivateUser(c.deactivationUser.value,true),
  previous:visual.dispositionLabel(c.selected.value?.disposition),reopenOutside:outside24,reopenText:'',reopenWindow:`${outside24?'Fuera':'Dentro'} de 24 h · reapertura manual no disponible.`,
  disposition:c.disposition.value,dispositions:c.dispositions,selectDisposition:(id:string)=>{c.disposition.value=id;},onDisposition:inp(c.disposition),note:c.closeNote.value,onNote:inp(c.closeNote),amount:c.saleAmount.value,onAmount:(e:Event)=>{const v=(e.target as HTMLInputElement).value;c.saleAmount.value=v===''?null:Number(v);},reference:c.saleReference.value,onReference:inp(c.saleReference),follow:c.followUpAt.value,onFollow:inp(c.followUpAt),farewell:menu?.close||'',closeError:c.closeError.value,canForce:has('conversation.close_all'),closeChat:c.closeChat,
  transferKind:c.transferKind.value,kinds:[{id:'agent',label:'Asesor',icon:'UserRound',desc:'Otro asesor con capacidad'},{id:'queue',label:'Cola general',icon:'Clock3',desc:'Primer asesor disponible'},{id:'ai',label:'CAP IA',icon:'Bot',desc:'La IA continúa el chat',disabled:true},{id:'menu',label:'Menú del bot',icon:'ListTree',desc:'El cliente vuelve a elegir'}],setKind:(id:string)=>{c.transferKind.value=id;if(id==='queue')c.transferTarget.value='';},target:c.transferTarget.value,selectTarget:(id:string)=>{c.transferTarget.value=id;},transferAgents:c.agents.value.filter((a:any)=>a.id!==c.agent.value?.id).map((a:any)=>({...a,name:c.users.value.find((u:any)=>u.id===a.id)?.name||a.username,initials:visual.initials(c.users.value.find((u:any)=>u.id===a.id)?.name||a.username),statusLabel:visual.statusLabel(a.status),dot:visual.dot(a.status),available:a.status==='ONLINE'&&a.active_chat_count<a.max_active_chats,selected:a.id===c.transferTarget.value,load:`${a.active_chat_count}/${a.max_active_chats}`,loadWidth:`${Math.min(100,a.active_chat_count/a.max_active_chats*100)}%`})),reason:c.transferReason.value,onReason:inp(c.transferReason),transfer:()=>{if(c.transferKind.value==='menu'){c.transferDialog.value=false;void c.action('return-to-bot');}else void c.transferChat();},returnPreview:menu?.returnToBot||'',
  userName:c.userName.value,onUserName:inp(c.userName),userLogin:c.userLogin.value,onUserLogin:inp(c.userLogin),userPassword:c.userPassword.value,onUserPassword:inp(c.userPassword),userRole:c.userRole.value,userRoles:roles.map(role=>({role,label:roleLabels[role]})),selectRole:(role:string)=>{c.userRole.value=role;},capacity:c.userCapacity.value,changeCapacity:(delta:number)=>{c.userCapacity.value=Math.min(100,Math.max(1,c.userCapacity.value+delta));},createUser:async()=>{await c.createUser();if(!c.userName.value)c.newUserDialog.value=false;}
 };
 return {metrics,team,diagnostics,settings,bot,modals};
}
