<script setup lang="ts">
import { ref, computed, nextTick, onMounted, onUnmounted } from 'vue';
import { io, type Socket } from 'socket.io-client';
import { Inbox, Users, Megaphone, ChartNoAxesCombined, Settings, Activity, Archive, Bell, Sun, Moon, LogOut, Search, Paperclip, Plus, MessageCircle, Clock3, Filter, Bot, FileText, Send, X, ChevronRight, LayoutDashboard, RefreshCw, AlertTriangle, UserRound } from '@lucide/vue';

type Mode='MENU'|'AI'|'HUMAN_PENDING'|'HUMAN_ACTIVE'|'CLOSING'|'CLOSED';
type Item={id:string;contact_id:string;name:string|null;phone:string|null;provider_contact_id:string;mode:Mode;assigned_to:string|null;unread_count:number;last_text:string|null;last_message_at:string|null};
type Msg={id:string;conversation_id:string;client_message_id?:string|null;correlation_id?:string|null;sequence:number;direction:string;sender_type:string;route:string;message_type:string;text:string;media_url:string|null;mime_type:string|null;file_name:string|null;media_size:number|null;duration:number|null;latitude:number|null;longitude:number|null;delivery_status:string|null;storage_status?:string|null;provider_timestamp:string|null;created_at:string;playable_available?:number};
type Menu={welcome:string;invalid:string;options:Record<string,{intent:string;reply:string}>;quickReplies:string[];claim:string;noAgent:string;returnToBot:string;close:string;image:string;audio:string;video:string;aiFailure:string;aiFailureNoAgent:string;aiFlood:string};
type Cursor={time:string;id:string}|null;
type Incident={id:string;code:string;severity:string;component:string;title:string;user_message:string;technical_message:string;last_seen_at:string;occurrence_count:number};
type User={id:string;username:string;name:string;role:string;active:number;status:string;active_chat_count:number;max_active_chats:number};
type Contact={id:string;name:string|null;phone:string|null;provider_contact_id:string;conversation_count:number;last_interaction_at:string|null};
const agent=ref<{id:string;username:string;role:string;permissions:string[]}|null>(null),username=ref(''),password=ref(''),authError=ref('');
const items=ref<Item[]>([]),selected=ref<Item|null>(null),messages=ref<Msg[]>([]),menu=ref<Menu|null>(null),metrics=ref<Record<string,number>>({});
const metricsRange=ref('today'),metricsAgentId=ref(''),dashboard=ref<{global:Record<string,number|null>;timings:Record<string,{mean:number|null;p50:number|null;p95:number|null}>;agents:Array<{id:string;username:string;status:string;active_chat_count:number;max_active_chats:number;closed:number;sales:number;consultations:number;transfersIn:number;transfersOut:number}>;sla:{criticalPending:number;criticalSeconds:number}}|null>(null);
const filter=ref('all'),search=ref(''),draft=ref(''),file=ref<File|null>(null),busy=ref(false),error=ref(''),settings=ref(false),health=ref<Record<string,string>>({});
const theme=ref<'dark'|'light'>('light'),chatScroll=ref<HTMLElement|null>(null),nextCursor=ref<Cursor>(null),hasOlder=ref(false),olderBusy=ref(false);
type Page='inbox'|'archive'|'dashboard'|'contacts'|'campaigns'|'metrics'|'team'|'diagnostics'|'settings';
const page=ref<Page>('inbox'),settingsSection=ref('general'),selectedUser=ref<User|null>(null),directorySearch=ref(''),teamSearch=ref('');
const contacts=ref<Contact[]>([]),contactOffset=ref<number|null>(0),selectedContact=ref<Contact|null>(null),contactHistory=ref<typeof history.value>([]);
let contactSearchTimer:ReturnType<typeof setTimeout>|undefined;
let contactRequestVersion=0;
const availableNav=computed(()=>[
  {id:'dashboard',label:'Inicio',icon:LayoutDashboard,visible:agent.value?.permissions.includes('metrics.view_all')},
  {id:'inbox',label:'Conversaciones',icon:Inbox,visible:true},
  {id:'archive',label:'Archivo',icon:Archive,visible:true},
  {id:'contacts',label:'Contactos',icon:Users,visible:true},
  {id:'campaigns',label:'Campañas',icon:Megaphone,visible:true},
  {id:'metrics',label:'Métricas',icon:ChartNoAxesCombined,visible:agent.value?.permissions.includes('metrics.view_all')},
  {id:'team',label:'Equipo',icon:UserRound,visible:agent.value?.permissions.includes('users.manage')},
  {id:'diagnostics',label:'Diagnóstico',icon:Activity,visible:agent.value?.permissions.includes('diagnostics.view')},
  {id:'settings',label:'Configuración',icon:Settings,visible:agent.value?.permissions.includes('settings.manage')||agent.value?.permissions.includes('audit.view')}
].filter(link=>link.visible));
const settingsLinks=[['general','General'],['whatsapp','WhatsApp'],['bot','Bot y menú'],['ai','IA'],['routing','Agentes y SLA'],['dispositions','Tipificaciones'],['users','Usuarios'],['diagnostics','Rendimiento'],['advanced','Herramientas avanzadas']];
function navigate(next:Page,section?:string,push=true){
  page.value=next;settings.value=next==='settings';
  if(section)settingsSection.value=section;
  if(next==='archive'||next==='inbox'){filter.value=next==='archive'?'closed':'all';void changeFilter();}
  if(next==='dashboard'||next==='metrics')void loadDashboard().catch(()=>{});
  if(next==='diagnostics')void loadIncidents().catch(()=>{});
  if(next==='team')void loadUsers().catch(()=>{});
  if(next==='contacts')void loadContacts().catch(()=>{});
  if(push)window.history.pushState(null,'',next==='settings'?`/settings/${settingsSection.value}`:next==='archive'?'/inbox/archive':`/${next}`);
}
function syncLocation(){const path=location.pathname;if(path.startsWith('/settings/'))navigate('settings',path.split('/')[2]||'general',false);else if(path==='/inbox/archive')navigate('archive',undefined,false);else if(['dashboard','contacts','campaigns','metrics','team','diagnostics'].includes(path.split('/')[1])){navigate(path.split('/')[1] as Page,undefined,false);if(path.startsWith('/contacts/'))void loadContactById(path.split('/')[2]);else selectedContact.value=null;}else navigate('inbox',undefined,false);}
function toggleTheme(){theme.value=theme.value==='dark'?'light':'dark';localStorage.setItem('cap-inbox-theme',theme.value);}
function changeTheme(value:string){theme.value=value==='dark'?'dark':'light';localStorage.setItem('cap-inbox-theme',theme.value);}
function scheduleContactSearch(){clearTimeout(contactSearchTimer);contactSearchTimer=setTimeout(()=>void loadContacts(),250);}
async function loadContacts(append=false){const version=++contactRequestVersion;try{const offset=append?contactOffset.value:0;if(offset===null)return;const result=await request<{contacts:Contact[];nextOffset:number|null}>(`/api/contacts?search=${encodeURIComponent(directorySearch.value)}&offset=${offset}`);if(version!==contactRequestVersion)return;contacts.value=append?[...contacts.value,...result.contacts]:result.contacts;contactOffset.value=result.nextOffset;}catch(e){if(version===contactRequestVersion)error.value=(e as Error).message;}}
async function openContact(contact:Contact,push=true){selectedContact.value=contact;if(push)window.history.pushState(null,'',`/contacts/${contact.id}`);try{contactHistory.value=(await request<{sessions:typeof contactHistory.value}>(`/api/contacts/${contact.id}/history`)).sessions;}catch{contactHistory.value=[];}}
async function loadContactById(id:string){try{const found=await request<{contact:Contact}>(`/api/contacts/${encodeURIComponent(id)}`);await openContact(found.contact,false);}catch(e){error.value=(e as Error).message;}}
function closeContact(){selectedContact.value=null;window.history.pushState(null,'','/contacts');}
const healthAlerts=computed(()=>['backend','database','worker','messagesync','messagesyncWebhook','n8nTransport','aiEngine','tunnel'].filter(key=>health.value[key]&&health.value[key]!=='online'&&health.value[key]!=='reachable'&&health.value[key]!=='healthy'));
const incidents=ref<Incident[]>([]),incidentCount=ref(0);
const lightbox=ref(''),zoom=ref(1),audioRate=ref(1);
const users=ref<User[]>([]),userName=ref(''),userLogin=ref(''),userPassword=ref(''),userRole=ref('AGENT'),userCapacity=ref(5),deactivateTarget=ref('QUEUE');
const history=ref<Array<{id:string;mode:string;created_at:string;disposition:string|null;assigned_to:string|null}>>([]),notes=ref<Array<{id:string;text:string;author:string;created_at:string}>>([]),noteDraft=ref('');
const tagOptions=ref<Array<{id:string;name:string;color:string}>>([]),conversationTags=ref<Array<{id:string;name:string;color:string}>>([]),tagToAdd=ref('');
const latencyWindow=ref(15),latencyReport=ref<{samples:number;metrics:Record<string,{count:number;p50:number|null;p95:number|null;p99:number|null}>;byRoute:Record<string,{count:number;routerMs:{p95:number|null};queueWaitMs:{p95:number|null}}> ;socket:{transports:Record<string,number>;pingP95Ms:number|null;reconnects:number}}|null>(null),messageTrace=ref<{messageId:string;trace:Record<string,string|number|null>}|null>(null);
const realtimeTransport=ref('desconectado'),realtimePing=ref<number|null>(null),reconnects=ref(0);
const closeDialog=ref(false),closeError=ref(false),disposition=ref(''),closeNote=ref(''),saleAmount=ref<number|null>(null),saleReference=ref(''),followUpAt=ref(''),transferDialog=ref(false),transferTarget=ref(''),transferReason=ref(''),agents=ref<Array<{id:string;username:string;status:string}>>([]),newMessages=ref(false);
const dispositions=[['SALE_COMPLETED','Venta completada'],['CONSULT_RESOLVED','Consulta atendida'],['QUOTE_SENT','Cotización enviada'],['FOLLOW_UP','Requiere seguimiento'],['NO_RESPONSE','Cliente dejó de responder'],['NO_SALE','No se concretó venta'],['WRONG_NUMBER','Número incorrecto'],['SPAM','Spam / contacto no válido'],['GENERAL_CLOSE','Cierre general'],['DUPLICATE','Duplicado'],['OTHER','Otro']];
let socket:Socket|null=null,searchTimer:ReturnType<typeof setTimeout>|undefined,heartbeatTimer:ReturnType<typeof setInterval>|undefined,healthTimer:ReturnType<typeof setInterval>|undefined,pendingRequestId:string|null=null,hasConnected=false;
const filters=[['all','Todos'],['pending','Esperando asesor'],['active','En atención'],['unread','No leídos'],['closed','Cerrados']];
const modeLabels:Record<Mode,string>={MENU:'BOT',AI:'IA',HUMAN_PENDING:'ESPERANDO',HUMAN_ACTIVE:'HUMANO',CLOSING:'CERRANDO',CLOSED:'CERRADO'};
const canSend=computed(()=>selected.value?.mode==='HUMAN_ACTIVE'&&(selected.value.assigned_to===agent.value?.username||agent.value?.permissions.includes('conversation.reply_all')));
const canTransfer=computed(()=>selected.value?.mode==='HUMAN_ACTIVE'&&(selected.value.assigned_to===agent.value?.username||agent.value?.permissions.includes('conversation.transfer_all')));
const failedMessage=computed(()=>messages.value.slice().reverse().find(m=>m.sender_type==='human'&&m.delivery_status==='failed'));
const sharedLocations=computed(()=>messages.value.filter(m=>m.message_type==='location'&&m.latitude!==null&&m.longitude!==null&&Math.abs(m.latitude)<=90&&Math.abs(m.longitude)<=180));
const initial=(name:string|null)=>((name||'?').trim()[0]||'?').toUpperCase();
const when=(date:string|null)=>date?new Date(date.endsWith('Z')||date.includes('+')?date:date.replace(' ','T')+'Z').toLocaleTimeString('es',{hour:'2-digit',minute:'2-digit'}):'';
const mediaSafe=(url:string|null)=>url?.startsWith('/api/media/')?url:'';
const displayMessageText=(m:Msg)=>m.message_type!=='text'&&/^\s*>?(IMAGE|AUDIO|VIDEO|DOCUMENT|STICKER)<?\s*$/i.test(m.text)?'':m.text;
const mapLink=(m:Msg)=>`https://www.openstreetmap.org/?mlat=${m.latitude}&mlon=${m.longitude}#map=16/${m.latitude}/${m.longitude}`;
const playable=(m:Msg)=>m.media_url&&m.playable_available&&['audio/ogg','audio/opus'].includes(m.mime_type||'')?`${m.media_url}?playable=1`:mediaSafe(m.media_url);
const audioSupported=(m:Msg)=>typeof document!=='undefined'&&Boolean(document.createElement('audio').canPlayType(m.mime_type||''));
function openMedia(url:string|null){const safe=mediaSafe(url);if(safe){lightbox.value=safe;zoom.value=1;}}
function setAudioRate(rate:number,button:HTMLButtonElement){audioRate.value=rate;const audio=button.closest('.bubble')?.querySelector('audio');if(audio)audio.playbackRate=rate;}
function onChatScroll(){if(chatScroll.value&&chatScroll.value.scrollTop<50)void loadOlder();if(chatScroll.value&&chatScroll.value.scrollHeight-chatScroll.value.scrollTop-chatScroll.value.clientHeight<110)newMessages.value=false;}
function scheduleSearch(){clearTimeout(searchTimer);searchTimer=setTimeout(()=>void loadList(),300);}
async function request<T>(path:string,init:RequestInit={}):Promise<T>{
  const response=await fetch(path,{credentials:'same-origin',...init,headers:init.body instanceof FormData?init.headers:{'Content-Type':'application/json',...init.headers}});
  if(response.status===401){agent.value=null;disconnect();throw new Error('Inicia sesión nuevamente');}
  const result=await response.json().catch(()=>null);if(!response.ok)throw new Error(typeof result?.error==='string'&&!/Unexpected token|<html|SQL|sqlite|constraint|stack trace|\bat\s+\w+\s*\(/i.test(result.error)?result.error:'No pudimos completar la solicitud. Intenta nuevamente.');
  if(result===null)throw new Error('No pudimos leer la respuesta. Intenta nuevamente.');return result as T;
}
async function login(){authError.value='';try{const r=await request<{agent:{id:string;username:string;role:string;permissions:string[]}}>('/api/login',{method:'POST',body:JSON.stringify({username:username.value,password:password.value})});agent.value=r.agent;password.value='';await boot();navigate('inbox');}catch(e){authError.value=(e as Error).message;}}
async function logout(){await request('/api/logout',{method:'POST'});agent.value=null;disconnect();}
async function loadList(append=false){
  try{
    const cursor=append&&nextCursor.value?`&cursorTime=${encodeURIComponent(nextCursor.value.time)}&cursorId=${encodeURIComponent(nextCursor.value.id)}`:'';
    const r=await request<{conversations:Item[];nextCursor:Cursor}>(`/api/conversations?filter=${filter.value}&search=${encodeURIComponent(search.value)}${cursor}`);
    items.value=append?[...items.value,...r.conversations.filter(i=>!items.value.some(old=>old.id===i.id))]:r.conversations;
    nextCursor.value=r.nextCursor;
    if(selected.value&&!append){const current=items.value.find(i=>i.id===selected.value?.id);if(current)selected.value=current;else if(filter.value!=='closed'){selected.value=null;messages.value=[];}}
  }catch(e){error.value=(e as Error).message;}
}
async function changeFilter(){selected.value=null;messages.value=[];nextCursor.value=null;await loadList();}
async function choose(item:Item){selected.value=item;messages.value=[];history.value=[];notes.value=[];conversationTags.value=[];newMessages.value=false;await loadMessages(true);void loadHistory(item);void loadNotes();void loadTags();void request(`/api/conversations/${item.id}/read`,{method:'POST'}).then(()=>loadList()).catch(()=>{});}
async function loadHistory(item:Item){try{history.value=(await request<{sessions:typeof history.value}>(`/api/contacts/${item.contact_id}/history`)).sessions;}catch{history.value=[];}}
async function openHistory(id:string){try{const result=await request<{conversation:Item;contact:{name:string|null;phone:string|null;provider_contact_id:string}}>(`/api/conversations/${id}`);const session=history.value.find(x=>x.id===id);selected.value={...result.conversation,...result.contact,assigned_to:session?.assigned_to||null,last_text:null};messages.value=[];await loadMessages(true);await loadNotes();}catch(e){error.value=(e as Error).message;}}
async function loadNotes(){if(!selected.value)return;const id=selected.value.id;try{const found=(await request<{notes:typeof notes.value}>(`/api/conversations/${id}/notes`)).notes;if(selected.value?.id===id)notes.value=found;}catch{notes.value=[];}}
async function addNote(){if(!selected.value||!noteDraft.value.trim())return;try{await request(`/api/conversations/${selected.value.id}/notes`,{method:'POST',body:JSON.stringify({text:noteDraft.value})});noteDraft.value='';await loadNotes();}catch(e){error.value=(e as Error).message;}}
async function loadTags(){if(!selected.value)return;const id=selected.value.id;try{const [options,assigned]=await Promise.all([request<{tags:typeof tagOptions.value}>('/api/tags'),request<{tags:typeof conversationTags.value}>(`/api/conversations/${id}/tags`)]);if(selected.value?.id===id){tagOptions.value=options.tags;conversationTags.value=assigned.tags;}}catch{conversationTags.value=[];}}
async function addTag(){if(!selected.value||!tagToAdd.value)return;try{await request(`/api/conversations/${selected.value.id}/tags`,{method:'POST',body:JSON.stringify({tagId:tagToAdd.value})});tagToAdd.value='';await loadTags();}catch(e){error.value=(e as Error).message;}}
async function loadMessages(force=false){
  if(!selected.value)return;const id=selected.value.id,el=chatScroll.value,stick=force||!el||el.scrollHeight-el.scrollTop-el.clientHeight<110;
  try{
    const r=await request<{messages:Msg[];hasMore:boolean}>(`/api/conversations/${id}/messages`);
    if(selected.value?.id!==id)return;
    messages.value=r.messages.sort((a,b)=>a.sequence-b.sequence);hasOlder.value=r.hasMore;
    await nextTick();if(stick&&chatScroll.value)chatScroll.value.scrollTop=chatScroll.value.scrollHeight;
  }catch(e){error.value=(e as Error).message;}
}
async function loadMissing(){
  if(!selected.value||!messages.value.length)return;
  const id=selected.value.id,last=messages.value.at(-1)!.sequence;
  const r=await request<{messages:Msg[]}>(`/api/conversations/${id}/messages?afterSequence=${last}`);
   if(selected.value?.id===id&&r.messages.length)for(const message of r.messages)applyMessage(message);
  if(selected.value?.id===id&&r.messages.length===100)await loadMessages(true);
}
async function loadOlder(){
  if(!selected.value||!hasOlder.value||olderBusy.value||!messages.value.length)return;
  olderBusy.value=true;const el=chatScroll.value,beforeHeight=el?.scrollHeight||0,id=selected.value.id;
  try{
    const r=await request<{messages:Msg[];hasMore:boolean}>(`/api/conversations/${id}/messages?beforeSequence=${messages.value[0].sequence}`);
    if(selected.value?.id===id){const ids=new Set(messages.value.map(x=>x.id));messages.value=[...r.messages.filter(x=>!ids.has(x.id)),...messages.value].sort((a,b)=>a.sequence-b.sequence);hasOlder.value=r.hasMore;await nextTick();if(el)el.scrollTop+=el.scrollHeight-beforeHeight;}
  }finally{olderBusy.value=false;}
}
function applyMessage(message:Msg){
  if(selected.value?.id!==message.conversation_id)return;
  const el=chatScroll.value,stick=!el||el.scrollHeight-el.scrollTop-el.clientHeight<110;
  const index=messages.value.findIndex(item=>item.id===message.id||Boolean(message.client_message_id&&item.client_message_id===message.client_message_id));
  if(index>=0)messages.value.splice(index,1);
  let left=0,right=messages.value.length;
  while(left<right){const middle=(left+right)>>1;if(messages.value[middle].sequence<=message.sequence)left=middle+1;else right=middle;}
  messages.value.splice(left,0,message);
  if(messages.value.length>200){messages.value.splice(0,messages.value.length-200);hasOlder.value=true;}
  void nextTick().then(()=>{if(stick&&chatScroll.value){chatScroll.value.scrollTop=chatScroll.value.scrollHeight;newMessages.value=false;}else if(message.direction==='inbound')newMessages.value=true;});
}
function updateSummary(summary:Item){
  const visible=filter.value==='closed'?summary.mode==='CLOSED':filter.value==='pending'?summary.mode==='HUMAN_PENDING':filter.value==='active'?['HUMAN_ACTIVE','CLOSING'].includes(summary.mode):filter.value==='unread'?['HUMAN_PENDING','HUMAN_ACTIVE','CLOSING'].includes(summary.mode)&&summary.unread_count>0:['HUMAN_PENDING','HUMAN_ACTIVE','CLOSING'].includes(summary.mode);
  const index=items.value.findIndex(item=>item.id===summary.id);
  if(index>=0)items.value.splice(index,1);
  if(visible&&(!search.value||[summary.name,summary.phone,summary.provider_contact_id,summary.last_text].some(v=>v?.toLowerCase().includes(search.value.toLowerCase()))))items.value.unshift(summary);
  if(selected.value?.id===summary.id){selected.value=summary;if(!visible&&filter.value!=='closed'){selected.value=null;messages.value=[];}}
}
function connect(){
  disconnect();socket=io({transports:['websocket','polling'],tryAllTransports:true,upgrade:true});
  socket.on('connect',()=>{if(hasConnected)reconnects.value++;hasConnected=true;realtimeTransport.value=socket?.io.engine.transport.name||'desconocido';socket?.io.engine.on('upgrade',transport=>{realtimeTransport.value=transport.name;});socket?.emit('agent:heartbeat');void loadList();void loadMissing();});
  socket.on('conversation:changed',({id,summary}:{id:string;summary?:Item})=>{if(summary)updateSummary(summary);else{void loadList();if(selected.value?.id===id)void loadMissing();}});
  const messageEvent=({message}:{message:Msg},ack?:((receipt:{receivedAt:string})=>void))=>{applyMessage(message);void nextTick().then(()=>ack?.({receivedAt:new Date().toISOString()}));};
  socket.on('message:created',messageEvent);socket.on('message:updated',messageEvent);socket.on('media:ready',messageEvent);
   socket.on('conversation.closed',({id}:{id:string})=>{if(selected.value?.id===id&&filter.value!=='closed'){selected.value=null;messages.value=[];}void loadList();});
   socket.on('inbox:refresh',()=>{void loadList();});
   socket.on('menu:changed',()=>void loadMenu());socket.on('connect_error',()=>{realtimeTransport.value='desconectado';error.value='Sin conexión en tiempo real';});
  heartbeatTimer=setInterval(()=>{if(socket?.connected){socket.emit('agent:heartbeat');const started=performance.now();socket.timeout(3000).emit('latency:ping',{},(err:Error|null)=>{if(err||!socket?.connected)return;realtimePing.value=Math.round(performance.now()-started);socket.emit('latency:report',{pingMs:realtimePing.value,reconnects:reconnects.value,transport:socket.io.engine.transport.name});});}},25000);
}
function disconnect(){if(heartbeatTimer)clearInterval(heartbeatTimer);heartbeatTimer=undefined;if(healthTimer)clearInterval(healthTimer);healthTimer=undefined;socket?.disconnect();socket=null;realtimeTransport.value='desconectado';}
async function loadMenu(){menu.value=await request<Menu>('/api/menu');}
async function loadHealth(){health.value=await request<Record<string,string>>('/api/health');}
async function loadMetrics(){metrics.value=await request<Record<string,number>>('/api/metrics');}
async function loadDashboard(){
  const day=(offset:number)=>new Date(Date.now()+offset*86400000).toISOString().slice(0,10);
  const from=metricsRange.value==='yesterday'?day(-1):metricsRange.value==='7'?day(-6):metricsRange.value==='30'?day(-29):day(0);
  const to=metricsRange.value==='yesterday'?day(0):day(1);
  dashboard.value=await request(`/api/metrics/dashboard?from=${from}&to=${to}${metricsAgentId.value?`&agentId=${encodeURIComponent(metricsAgentId.value)}`:''}`);
}
async function loadIncidents(){const result=await request<{active:number;incidents:Incident[]}>('/api/diagnostics');incidents.value=result.incidents;incidentCount.value=result.active;}
async function loadLatency(){latencyReport.value=await request(`/api/diagnostics/latency?minutes=${latencyWindow.value}`);}
async function showTrace(messageId:string){try{messageTrace.value=await request(`/api/diagnostics/latency/${messageId}`);}catch(e){error.value=(e as Error).message;}}
async function resolveIncident(id:string){try{await request(`/api/diagnostics/${id}/resolve`,{method:'POST'});await loadIncidents();}catch(e){error.value=(e as Error).message;}}
async function copyDiagnostic(){try{const report=await request<object>('/api/diagnostics/report');await navigator.clipboard.writeText(JSON.stringify(report,null,2));error.value='Diagnóstico copiado sin credenciales';}catch(e){error.value=(e as Error).message;}}
async function loadUsers(){users.value=(await request<{users:User[]}>('/api/users')).users;}
async function createUser(){try{await request('/api/users',{method:'POST',body:JSON.stringify({name:userName.value,username:userLogin.value,password:userPassword.value,role:userRole.value,maxActiveChats:userCapacity.value})});userName.value='';userLogin.value='';userPassword.value='';await loadUsers();}catch(e){error.value=(e as Error).message;}}
async function deactivateUser(user:User){if(!window.confirm(`¿Desactivar ${user.username}? ${user.active_chat_count} chats activos serán reasignados o enviados a cola.`))return;try{await request(`/api/users/${user.id}`,{method:'PATCH',body:JSON.stringify({active:false,deactivateHandling:deactivateTarget.value})});await loadUsers();await loadList();}catch(e){error.value=(e as Error).message;}}
async function boot(){await Promise.allSettled([loadList(),loadMenu(),...(agent.value?.permissions.includes('audit.view')?[loadHealth(),loadLatency()]:[]),...(agent.value?.permissions.includes('metrics.view_all')?[loadMetrics(),loadDashboard()]:[]),...(agent.value?.permissions.includes('diagnostics.view')?[loadIncidents()]:[]),...(agent.value?.permissions.includes('users.manage')?[loadUsers()]:[])]);connect();if(agent.value?.permissions.includes('audit.view'))healthTimer=setInterval(()=>{void loadHealth().catch(()=>{health.value={...health.value,backend:'offline'};});if(agent.value?.permissions.includes('diagnostics.view'))void loadIncidents().catch(()=>{});},30000);}
async function action(kind:'claim'|'return-to-bot'){
  if(!selected.value||busy.value)return;busy.value=true;error.value='';const id=selected.value.id;
  try{await request(`/api/conversations/${id}/${kind}`,{method:'POST'});await loadList();await loadMissing();}catch(e){error.value=(e as Error).message;await loadList();await loadMissing();}finally{busy.value=false;}
}
async function closeChat(force=false){if(!selected.value||!disposition.value||busy.value)return;busy.value=true;error.value='';const id=selected.value.id;try{const result=await request<{status?:string}>(`/api/conversations/${id}/close`,{method:'POST',body:JSON.stringify({disposition:disposition.value,note:closeNote.value,saleAmount:saleAmount.value,saleReference:saleReference.value,followUpAt:followUpAt.value?new Date(followUpAt.value).toISOString():null,force})});closeDialog.value=false;closeError.value=false;disposition.value='';closeNote.value='';saleAmount.value=null;saleReference.value='';followUpAt.value='';if(result.status==='closing')error.value='Cierre en proceso. Se archivará solo cuando MessageSync confirme el envío.';else await loadList();}catch(e){error.value=(e as Error).message;closeError.value=true;}finally{busy.value=false;}}
async function openTransfer(){try{const r=await request<{agents:Array<{id:string;username:string;status:string}>}>('/api/agents');agents.value=r.agents;transferTarget.value='';transferDialog.value=true;}catch(e){error.value=(e as Error).message;}}
async function transferChat(){if(!selected.value||busy.value)return;busy.value=true;try{await request(`/api/conversations/${selected.value.id}/transfer`,{method:'POST',body:JSON.stringify({toAgentId:transferTarget.value||null,reason:transferReason.value})});transferDialog.value=false;transferReason.value='';selected.value=null;messages.value=[];await loadList();}catch(e){error.value=(e as Error).message;}finally{busy.value=false;}}
async function send(){
  if(!selected.value||!canSend.value||busy.value||(!draft.value.trim()&&!file.value))return;
  busy.value=true;error.value='';const id=selected.value.id,body=new FormData(),clientId=pendingRequestId||crypto.randomUUID();pendingRequestId=clientId;
  const text=draft.value.trim(),attachment=file.value,createdAt=new Date().toISOString();
  body.append('clientRequestId',clientId);body.append('clientCreatedAt',createdAt);body.append('text',text);if(attachment)body.append('file',attachment);
  const optimistic:Msg={id:`optimistic:${clientId}`,client_message_id:clientId,conversation_id:id,sequence:(messages.value.at(-1)?.sequence||0)+.5,direction:'outbound',sender_type:'human',route:'HUMAN',message_type:attachment?.type.startsWith('image/')?'image':attachment?'document':'text',text,media_url:null,mime_type:attachment?.type||null,file_name:attachment?.name||null,media_size:attachment?.size||null,duration:null,latitude:null,longitude:null,delivery_status:'sending',storage_status:null,provider_timestamp:null,created_at:createdAt};
  applyMessage(optimistic);draft.value='';file.value=null;
  try{
    const result=await request<{messageId:string;status:string}>(`/api/conversations/${id}/messages`,{method:'POST',body});
    pendingRequestId=null;
    const index=messages.value.findIndex(m=>m.client_message_id===clientId);
    if(index>=0&&messages.value[index].id.startsWith('optimistic:'))messages.value.splice(index,1,{...messages.value[index],id:result.messageId,delivery_status:result.status});
    if(!socket?.connected)await loadMessages();
  }catch(e){error.value=`No se confirmó el envío. Revisa el estado antes de reintentar. ${(e as Error).message}`;pendingRequestId=null;const index=messages.value.findIndex(m=>m.client_message_id===clientId);if(index>=0&&messages.value[index].id.startsWith('optimistic:'))messages.value[index].delivery_status='unknown';}
  finally{busy.value=false;}
}
async function saveMenu(){if(!menu.value)return;try{await request('/api/menu',{method:'PUT',body:JSON.stringify(menu.value)});error.value='Menú guardado';}catch(e){error.value=(e as Error).message;}}
async function retryFailed(){if(!selected.value||!failedMessage.value||busy.value)return;busy.value=true;try{await request(`/api/conversations/${selected.value.id}/messages/${failedMessage.value.id}/retry`,{method:'POST'});await loadMessages();}catch(e){error.value=(e as Error).message;await loadMessages();}finally{busy.value=false;}}
async function retryIncomingMedia(msg:Msg){if(!selected.value||busy.value)return;busy.value=true;try{await request(`/api/conversations/${selected.value.id}/media/${msg.id}/retry`,{method:'POST'});}catch(e){error.value=(e as Error).message;}finally{busy.value=false;}}
onMounted(async()=>{const stored=localStorage.getItem('cap-inbox-theme');theme.value=stored==='dark'?'dark':'light';window.addEventListener('popstate',syncLocation);try{const r=await request<{agent:{id:string;username:string;role:string;permissions:string[]}}>('/api/me');agent.value=r.agent;await boot();syncLocation();}catch{}});
onUnmounted(()=>{clearTimeout(searchTimer);clearTimeout(contactSearchTimer);disconnect();window.removeEventListener('popstate',syncLocation);});
</script>

<template>
 <div :class="['app-shell',theme]">
  <div v-if="!agent" class="login-page"><div class="login-layout"><section class="login-form-pane"><img :src="`/brand/cap-inbox-logo-${theme}.svg`" alt="CAP Inbox · Centro de Atención Híbrido" class="login-logo"><form class="login-card" @submit.prevent="login"><h1>Bienvenido</h1><p>Inicia sesión para continuar.</p><label>Usuario<input v-model="username" autocomplete="username" placeholder="tu@empresa.com" required></label><label>Contraseña<input v-model="password" type="password" autocomplete="current-password" required></label><span v-if="authError" class="form-error" role="alert">{{authError}}</span><button class="primary wide">Iniciar sesión</button><div class="login-foot"><span>Tu espacio de atención, en un solo lugar.</span><button type="button" class="link-button" :aria-label="theme==='dark'?'Cambiar a modo claro':'Cambiar a modo oscuro'" @click="toggleTheme"><Sun v-if="theme==='dark'" :size="17"/><Moon v-else :size="17"/></button></div></form></section><section class="login-brand-pane"><h2>Conversaciones<br>que impulsan<br>tu negocio.</h2><div class="login-line"></div><p>Atiende hoy.<br>Mide mañana.<br>Crece con contexto.</p></section></div></div>
  <template v-else>
    <header class="topbar"><button class="brand" aria-label="Ir a Inbox" @click="navigate('inbox')"><img :src="`/brand/cap-inbox-logo-${theme}.svg`" alt="CAP Inbox · Centro de Atención Híbrido"></button><div class="breadcrumbs"><span>{{page==='inbox'||page==='archive'?'Conversaciones':page==='settings'?'Configuración':'CAP Inbox'}}</span><ChevronRight :size="15"/><strong>{{page==='inbox'?'Bandeja de entrada':page==='archive'?'Archivo':page==='settings'?settingsLinks.find(s=>s[0]===settingsSection)?.[1]:availableNav.find(n=>n.id===page)?.label}}</strong></div><div class="topbar-right"><span class="live" :title="`Transporte: ${realtimeTransport} · ping ${realtimePing??'—'} ms · reconexiones ${reconnects}`"><span class="live-dot"></span>{{realtimeTransport==='desconectado'?'Sin conexión':'En línea'}}</span><button class="icon-button" :aria-label="theme==='dark'?'Modo claro':'Modo oscuro'" @click="toggleTheme"><Sun v-if="theme==='dark'" :size="19"/><Moon v-else :size="19"/></button><button class="icon-button" aria-label="Notificaciones" :title="`${incidentCount} incidencias activas`" @click="navigate('diagnostics')"><Bell :size="19"/><span v-if="incidentCount" class="notification-count">{{incidentCount}}</span></button><button v-if="agent.permissions.includes('settings.manage')" class="icon-button" aria-label="Configuración" @click="navigate('settings','general')"><Settings :size="19"/></button><div class="topbar-user"><span class="user-avatar">{{initial(agent.username)}}</span><span><strong>{{agent.username}}</strong><small>{{agent.role==='SUPERADMIN'?'Superadmin':agent.role==='ADMIN'?'Administrador':'Asesor'}}</small></span></div><button class="icon-button" aria-label="Cerrar sesión" @click="logout"><LogOut :size="18"/></button></div></header>
    <nav class="sidebar" aria-label="Navegación principal"><button v-if="agent.permissions.includes('conversation.reply_all')||agent.permissions.includes('conversation.claim')" class="primary sidebar-create" disabled title="Crear conversaciones todavía no está soportado por el servidor"><Plus :size="18"/> Nueva conversación</button><div class="sidebar-links"><button v-for="link in availableNav" :key="link.id" :class="['sidebar-link',page===link.id?'active':'']" @click="navigate(link.id as Page,link.id==='settings'?'general':undefined)"><component :is="link.icon" :size="19" :stroke-width="1.8"/><span>{{link.label}}</span><span v-if="link.id==='inbox'&&items.length" class="side-count">{{items.length}}</span><span v-if="link.id==='diagnostics'&&incidentCount" class="side-count">{{incidentCount}}</span></button></div><div class="sidebar-bottom"><img :src="`/brand/cap-inbox-logo-${theme}.svg`" alt="CAP Inbox"><span>MÁS CONVERSACIONES<br>UN MEJOR MAÑANA</span><i></i></div></nav>
    <div v-if="error" class="notice" role="status">{{error}} <button @click="error=''">×</button></div>
    <div v-if="agent.permissions.includes('audit.view')&&healthAlerts.length" class="health-alert" role="alert">⚠ Servicios que requieren atención: {{healthAlerts.join(', ')}} <button @click="loadHealth">Actualizar</button></div>
    <div v-if="agent.permissions.includes('diagnostics.view')&&incidentCount" class="health-alert" role="alert">{{incidentCount}} incidencias activas <button @click="navigate('diagnostics')">Ver diagnóstico</button></div>
    <div v-if="page==='inbox'&&canSend&&failedMessage" class="retry-notice">El envío falló. Comprueba primero si llegó al cliente para evitar duplicados. <button :disabled="busy" @click="retryFailed">Reintentar envío</button></div>
    <main v-if="page==='dashboard'||page==='metrics'" class="page-scroll"><div class="page-heading"><div><h1>{{page==='dashboard'?`Hola, ${agent.username}`:'Métricas'}}</h1><p>Rendimiento de atención y resultados reales del período.</p></div><div class="metric-filters"><select v-model="metricsRange" aria-label="Período" @change="loadDashboard"><option value="today">Hoy</option><option value="yesterday">Ayer</option><option value="7">Últimos 7 días</option><option value="30">Últimos 30 días</option></select><select v-model="metricsAgentId" aria-label="Agente" @change="loadDashboard"><option value="">Todos los agentes</option><option v-for="person in dashboard?.agents" :key="person.id" :value="person.id">{{person.username}}</option></select></div></div><template v-if="dashboard"><div class="kpi-grid"><article v-for="[label,value] in [['Conversaciones',dashboard.global.conversations],['Mensajes',(dashboard.global.inbound||0)+(dashboard.global.outbound||0)],['Ventas',dashboard.global.sales],['Primera respuesta',dashboard.timings.firstHumanResponse.p50===null?'—':`${dashboard.timings.firstHumanResponse.p50} s`]]" :key="label" class="stat-card"><span>{{label}}</span><strong>{{value??0}}</strong></article></div><div class="dashboard-charts"><section class="card"><h2>Resultados de conversaciones</h2><div class="result-list"><div v-for="[label,key] in [['Ventas','sales'],['Consultas','consultations'],['Cotizaciones','quotes'],['Seguimientos','followups']]" :key="key"><span>{{label}}</span><strong>{{dashboard.global[key]??0}}</strong><div class="result-track"><i :style="{width:`${Math.min(100,100*(dashboard.global[key]||0)/Math.max(1,dashboard.global.conversations||0))}%`}"></i></div></div></div></section><section class="card"><h2>Tiempos de atención</h2><div v-for="(timing,key) in dashboard.timings" :key="key" class="status-row"><span>{{({wait:'Espera',firstHumanResponse:'Primera respuesta humana',handling:'Atención',aiLatencySeconds:'IA (s)'} as Record<string,string>)[key]||key}}</span><strong>P50 {{timing.p50??'—'}} · P95 {{timing.p95??'—'}} s</strong></div><div class="status-row"><span>Pendientes fuera de SLA</span><strong>{{dashboard.sla.criticalPending}}</strong></div></section></div><section class="card"><h2>Operación en vivo</h2><div class="table-wrap"><table><thead><tr><th>Agente</th><th>Estado</th><th>Chats</th><th>Cerrados</th><th>Ventas</th><th>Consultas</th></tr></thead><tbody><tr v-for="person in dashboard.agents" :key="person.id"><td>{{person.username}}</td><td><span class="status-chip" :class="person.status==='ONLINE'?'good':'warn'">{{person.status}}</span></td><td>{{person.active_chat_count}}/{{person.max_active_chats}}</td><td>{{person.closed}}</td><td>{{person.sales}}</td><td>{{person.consultations}}</td></tr></tbody></table></div></section></template><div v-else class="card empty-state">Cargando métricas…</div></main>
    <main v-else-if="page==='contacts'" class="page-scroll"><div class="page-heading"><div><h1>Contactos</h1><p>Directorio de contactos de las conversaciones a las que tienes acceso.</p></div></div><div class="search page-search"><Search :size="17"/><input v-model="directorySearch" placeholder="Buscar por nombre o teléfono" aria-label="Buscar contactos" @input="scheduleContactSearch"></div><section class="card"><div class="table-wrap"><table><thead><tr><th>Nombre</th><th>Teléfono</th><th>Canal</th><th>Conversaciones</th><th>Última interacción</th><th></th></tr></thead><tbody><tr v-for="person in contacts" :key="person.id"><td><span class="table-person"><span class="avatar">{{initial(person.name)}}</span>{{person.name||'Contacto sin nombre'}}</span></td><td>{{person.phone||'—'}}</td><td>WhatsApp</td><td>{{person.conversation_count}}</td><td>{{when(person.last_interaction_at)}}</td><td><button class="link-button" @click="openContact(person)">Ver perfil</button></td></tr></tbody></table></div><div v-if="!contacts.length" class="empty-state">No encontramos contactos con esta búsqueda.</div><button v-if="contactOffset!==null" class="outline" @click="loadContacts(true)">Cargar más contactos</button></section><section v-if="selectedContact" class="card contact-profile"><div class="card-heading"><div class="table-person"><span class="avatar large">{{initial(selectedContact.name)}}</span><div><h2>{{selectedContact.name||'Contacto sin nombre'}}</h2><p class="muted">{{selectedContact.phone||selectedContact.provider_contact_id}} · WhatsApp</p></div></div><button class="icon-button" aria-label="Cerrar perfil" @click="closeContact"><X :size="18"/></button></div><h3>Historial de conversaciones</h3><div v-for="session in contactHistory" :key="session.id" class="status-row"><span>{{new Date(session.created_at).toLocaleDateString('es')}} · {{session.assigned_to||'Sin asignar'}}</span><strong>{{session.disposition||session.mode}}</strong><button class="link-button" @click="navigate('archive');openHistory(session.id)">Ver sesión</button></div><p v-if="!contactHistory.length" class="muted">No hay sesiones accesibles para este contacto.</p></section></main>
    <main v-else-if="page==='campaigns'" class="page-scroll"><div class="page-heading"><div><h1>Campañas</h1><p>Mensajería a escala, separada de la bandeja de atención.</p></div></div><section class="card empty-state"><Megaphone :size="38" :stroke-width="1.4"/><h2>Campañas aún no disponibles</h2><p>Esta instalación no dispone de una API de campañas. No se ha enviado ni programado ningún mensaje desde esta vista.</p></section></main>
    <main v-else-if="page==='team'" class="page-scroll"><div class="page-heading"><div><h1>Equipo</h1><p>Usuarios, roles, disponibilidad y capacidad.</p></div><button class="outline" @click="selectedUser=null;settingsSection='users';navigate('settings','users')"><Plus :size="16"/> Nuevo usuario</button></div><div class="search page-search"><Search :size="17"/><input v-model="teamSearch" placeholder="Buscar usuarios" aria-label="Buscar usuarios"></div><section class="card"><div class="table-wrap"><table><thead><tr><th>Nombre</th><th>Rol</th><th>Estado</th><th>Chats</th><th>Capacidad</th><th>Acciones</th></tr></thead><tbody><tr v-for="person in users.filter(u=>[u.name,u.username].some(v=>v.toLowerCase().includes(teamSearch.toLowerCase())))" :key="person.id"><td><span class="table-person"><span class="avatar">{{initial(person.name||person.username)}}</span>{{person.name||person.username}}</span></td><td>{{person.role}}</td><td><span :class="['status-chip',person.status==='ONLINE'?'good':'warn']">{{person.status}}</span></td><td>{{person.active_chat_count}}</td><td>{{person.active_chat_count}} / {{person.max_active_chats}}</td><td><button class="link-button" @click="selectedUser=person">Ver detalle</button></td></tr></tbody></table></div><div v-if="!users.length" class="empty-state">No hay usuarios visibles.</div></section><section class="card"><h2>Roles y permisos</h2><p class="muted">Los permisos efectivos se aplican en el servidor; no pueden ampliarse desde esta pantalla.</p><div class="role-grid"><div v-for="role in ['AGENT','ADMIN','SUPERADMIN']" :key="role" class="role-card"><strong>{{role}}</strong><span>{{users.filter(u=>u.role===role&&u.active).length}} usuarios activos</span></div></div></section></main>
    <main v-else-if="page==='diagnostics'" class="page-scroll"><div class="page-heading"><div><h1>Diagnóstico del sistema</h1><p>Salud, rendimiento e incidencias de la operación.</p></div><button class="outline" @click="loadHealth();loadIncidents();loadLatency()"><RefreshCw :size="16"/> Actualizar</button></div><div class="health-grid"><article v-for="(value,key) in health" :key="key" class="card health-card"><span>{{({backend:'Backend',database:'Base de datos',worker:'Worker',messagesync:'MessageSync',messagesyncWebhook:'Webhook',n8nTransport:'n8n',aiEngine:'AI Engine',tunnel:'Túnel'} as Record<string,string>)[key]||key}}</span><strong :class="['health-value',['healthy','reachable','online'].includes(value)?'good':'warn']">{{value}}</strong></article></div><section class="card"><h2>Incidencias activas <span class="count">{{incidentCount}}</span></h2><div v-for="incident in incidents" :key="incident.id" class="incident-card"><AlertTriangle :size="19"/><div><strong>{{incident.title}}</strong><p>{{incident.user_message}}</p><small>{{incident.occurrence_count}} ocurrencias</small><details v-if="agent.permissions.includes('audit.view')"><summary>Detalle técnico</summary><code>{{incident.code}} — {{incident.technical_message}}</code></details><button v-if="agent.permissions.includes('diagnostics.retry')" class="link-button" @click="resolveIncident(incident.id)">Marcar resuelto</button></div></div><p v-if="!incidents.length" class="muted">No hay incidencias activas registradas.</p></section><section v-if="agent.permissions.includes('audit.view')" class="card"><h2>Latencia observada <button class="link-button" @click="loadLatency">Actualizar</button></h2><p class="muted">P50 / P95 / P99 en milisegundos. Los tramos no medidos se muestran como «—».</p><div v-for="(stats,key) in latencyReport?.metrics" :key="key" class="status-row"><span>{{key.replaceAll('_',' ')}}</span><strong>{{stats.p50??'—'}} / {{stats.p95??'—'}} / {{stats.p99??'—'}}</strong></div><button class="outline" @click="copyDiagnostic">Copiar reporte sin credenciales</button></section></main>
    <div v-else-if="settings" class="settings-page"><nav class="settings-nav" aria-label="Secciones de configuración"><h2>Configuración</h2><button v-for="[id,label] in settingsLinks.filter(s=>s[0]!=='users'||agent?.permissions.includes('users.manage'))" :key="id" :class="['settings-link',settingsSection===id?'active':'']" @click="navigate('settings',id)">{{label}}</button></nav><main class="settings-content"><div class="page-heading"><div><h1>{{settingsLinks.find(s=>s[0]===settingsSection)?.[1]}}</h1><p>{{settingsSection==='bot'?'Respuestas automáticas y rutas antes de IA.':settingsSection==='whatsapp'?'Estado operativo del canal y webhook.':settingsSection==='ai'?'Disponibilidad y tiempo de respuesta del AI Engine.':settingsSection==='routing'?'Asignación, capacidad y atención.':'Preferencias y herramientas del centro de atención.'}}</p></div></div>
      <section v-if="settingsSection==='general'" class="card"><h2>Experiencia de CAP Inbox</h2><div class="settings-fields"><label>Nombre del producto<input value="CAP Inbox" readonly></label><label>Idioma<input value="Español" readonly></label><label>Tema<select :value="theme" @change="changeTheme(($event.target as HTMLSelectElement).value)"><option value="light">Claro</option><option value="dark">Oscuro</option></select></label><label>Conexión en tiempo real<input :value="realtimeTransport" readonly></label></div><p class="muted">La preferencia de tema se guarda en este navegador.</p></section>
      <section v-else-if="settingsSection==='bot'&&menu" class="card bot-card"><div class="card-heading"><h2>Menú inicial</h2><button v-if="agent.permissions.includes('settings.manage')" class="primary" @click="saveMenu">Guardar cambios</button></div><label>Mensaje de bienvenida<textarea v-model="menu.welcome" rows="5" :readonly="!agent.permissions.includes('settings.manage')"></textarea></label><h3>Opciones del menú</h3><div v-for="(entry,key) in menu.options" :key="key" class="bot-option"><span class="option-number">{{key}}</span><label>Respuesta<textarea v-model="entry.reply" rows="2" :readonly="!agent.permissions.includes('settings.manage')"></textarea></label><span :class="['mode-badge',entry.intent.toLowerCase().includes('human')?'human_active':'ai']">{{entry.intent}}</span></div><details class="bot-fallback"><summary>Mensajes de respaldo y cierre</summary><label>Sin asesores<textarea v-model="menu.noAgent" rows="3"></textarea></label><label>IA no disponible<textarea v-model="menu.aiFailureNoAgent" rows="3"></textarea></label><label>Cierre<textarea v-model="menu.close" rows="3"></textarea></label></details><p class="muted">Los demás mensajes del bot permanecen editables en Herramientas avanzadas.</p></section>
      <section v-else-if="settingsSection==='whatsapp'" class="card"><h2>Canal WhatsApp</h2><div class="health-grid"><div class="status-row"><span>MessageSync</span><strong>{{health.messagesync||'Sin datos'}}</strong></div><div class="status-row"><span>Webhook</span><strong>{{health.messagesyncWebhook||'Sin datos'}}</strong></div><div class="status-row"><span>Backend</span><strong>{{health.backend||'Sin datos'}}</strong></div></div><p class="muted">Las credenciales y el número del canal no se exponen en la interfaz.</p><button class="outline" @click="loadHealth">Actualizar estado</button></section>
      <section v-else-if="settingsSection==='ai'" class="card"><h2>AI Engine</h2><div class="health-grid"><div class="status-row"><span>Motor</span><strong>{{health.aiEngine||'Sin datos'}}</strong></div><div class="status-row"><span>Transporte n8n</span><strong>{{health.n8nTransport||'Sin datos'}}</strong></div><div class="status-row"><span>P95 observado</span><strong>{{dashboard?.timings.aiLatencySeconds.p95??'—'}} s</strong></div></div><p class="muted">La configuración del motor se administra en el servidor; aquí se muestran únicamente valores observados.</p></section>
      <section v-else-if="settingsSection==='routing'" class="card"><h2>Agentes y capacidad</h2><p>Disponibilidad y carga actual, según el heartbeat del servidor.</p><div v-for="person in dashboard?.agents" :key="person.id" class="status-row"><span>{{person.username}} · {{person.status}}</span><strong>{{person.active_chat_count}} / {{person.max_active_chats}} chats</strong></div><button class="outline" @click="navigate('team')">Ver equipo</button></section>
      <section v-else-if="settingsSection==='dispositions'" class="card"><h2>Tipificaciones de cierre</h2><div v-for="[value,label] in dispositions" :key="value" class="status-row"><span>{{label}}</span><small>{{value}}</small></div><p class="muted">Los cambios en estas opciones requieren soporte del servidor.</p></section>
      <section v-else-if="settingsSection==='users'&&agent.permissions.includes('users.manage')" class="card"><h2>Nuevo usuario</h2><form class="user-form" @submit.prevent="createUser"><label>Nombre<input v-model="userName" required minlength="2"></label><label>Usuario<input v-model="userLogin" required minlength="3"></label><label>Contraseña nueva (mínimo 12 caracteres)<input v-model="userPassword" type="password" required minlength="12" autocomplete="new-password"></label><label>Rol<select v-model="userRole"><option value="AGENT">Agente</option><option value="ADMIN">Administrador</option><option value="SUPERADMIN">Superadmin</option></select></label><label>Capacidad máxima<input v-model.number="userCapacity" type="number" min="1" max="100"></label><button class="primary">Crear usuario</button></form></section>
      <section v-else-if="settingsSection==='diagnostics'" class="card"><h2>Rendimiento</h2><div v-for="(stats,key) in latencyReport?.metrics" :key="key" class="status-row"><span>{{key.replaceAll('_',' ')}}</span><strong>P50 {{stats.p50??'—'}} · P95 {{stats.p95??'—'}} · P99 {{stats.p99??'—'}} ms</strong></div><button class="outline" @click="navigate('diagnostics')">Abrir diagnóstico completo</button></section>
      <div v-if="settingsSection==='advanced'" class="settings-grid">
        <section class="settings-card"><template v-if="agent.permissions.includes('audit.view')"><h2>Estado de servicios <button class="link-button" @click="loadHealth">Actualizar</button></h2><div v-for="(value,key) in health" :key="key" class="status-row"><span>{{key}}</span><span :class="['status-chip',['online','reachable','healthy'].includes(value)?'good':'warn']">{{value}}</span></div><p class="muted small-text">Reachable indica transporte; healthy requiere un éxito reciente de CAP IA.</p></template><template v-if="agent.permissions.includes('metrics.view_all')"><h2>Métricas <button class="link-button" @click="loadDashboard">Actualizar</button></h2><div class="metric-filters"><select v-model="metricsRange" @change="loadDashboard"><option value="today">Hoy</option><option value="yesterday">Ayer</option><option value="7">7 días</option><option value="30">30 días</option></select><select v-model="metricsAgentId" @change="loadDashboard"><option value="">Todos los agentes</option><option v-for="person in dashboard?.agents" :key="person.id" :value="person.id">{{person.username}}</option></select></div><template v-if="dashboard"><div v-for="(value,key) in dashboard.global" :key="key" class="status-row"><span>{{key.replaceAll('_',' ')}}</span><strong>{{value??0}}</strong></div><h3>Tiempos humanos (segundos)</h3><div v-for="(time,key) in dashboard.timings" :key="key" class="status-row"><span>{{key}}</span><strong>Media {{time.mean??'—'}} · P50 {{time.p50??'—'}} · P95 {{time.p95??'—'}}</strong></div><p v-if="dashboard.sla.criticalPending" class="form-error">{{dashboard.sla.criticalPending}} pendientes superan {{dashboard.sla.criticalSeconds}} segundos.</p><h3>Equipo</h3><div v-for="person in dashboard.agents" :key="person.id" class="status-row"><span>{{person.username}} · {{person.status}} · {{person.active_chat_count}}/{{person.max_active_chats}}</span><strong>{{person.closed}} cerrados · {{person.sales}} ventas · {{person.consultations}} consultas</strong></div></template></template></section>
        <section v-if="agent.permissions.includes('settings.manage')&&menu" class="settings-card"><h2>Mensajes de WhatsApp</h2><label>Menú inicial<textarea v-model="menu.welcome" rows="7"></textarea></label><label v-for="(entry,key) in menu.options" :key="key">Opción {{key}} · {{entry.intent}}<textarea v-model="entry.reply" rows="3"></textarea></label><label>Sin asesores<textarea v-model="menu.noAgent" rows="4"></textarea></label><label>IA caída sin asesores<textarea v-model="menu.aiFailureNoAgent" rows="3"></textarea></label><label>Mensaje de cierre<textarea v-model="menu.close" rows="4"></textarea></label><button class="primary" @click="saveMenu">Guardar menú</button></section>
        <section v-if="agent.permissions.includes('diagnostics.view')" class="settings-card"><h2>Centro de incidencias <button class="link-button" @click="loadIncidents">Actualizar</button></h2><p>{{incidentCount}} incidencias activas</p><button class="outline" @click="copyDiagnostic">Copiar diagnóstico sin secretos</button><div v-for="incident in incidents" :key="incident.id" class="incident-card"><strong>{{incident.severity}} · {{incident.title}}</strong><p>{{incident.user_message}}</p><small>{{incident.component}} · {{incident.last_seen_at}} · {{incident.occurrence_count}} ocurrencias</small><details><summary>Detalle técnico</summary><code>{{incident.code}} — {{incident.technical_message}}</code></details><button v-if="agent.permissions.includes('diagnostics.retry')" class="link-button" @click="resolveIncident(incident.id)">Marcar resuelto</button></div></section>
        <section v-if="agent.permissions.includes('audit.view')" class="settings-card"><h2>Diagnóstico → Rendimiento <button class="link-button" @click="loadLatency">Actualizar</button></h2><label>Ventana<select v-model.number="latencyWindow" @change="loadLatency"><option :value="15">15 minutos</option><option :value="60">1 hora</option><option :value="1440">24 horas</option></select></label><p>El tiempo del evento del proveedor puede no incluir el tramo original de WhatsApp; valores «—» aún no se midieron.</p><template v-if="latencyReport"><p>{{latencyReport.samples}} trazas recientes · WebSocket {{latencyReport.socket.transports.websocket||0}} · Polling {{latencyReport.socket.transports.polling||0}} · ping P95 {{latencyReport.socket.pingP95Ms??'—'}} ms · reconexiones {{latencyReport.socket.reconnects}}</p><div v-for="(stats,key) in latencyReport.metrics" :key="key" class="status-row"><span>{{key.replaceAll('_',' ')}} ({{stats.count}})</span><strong>P50 {{stats.p50??'—'}} · P95 {{stats.p95??'—'}} · P99 {{stats.p99??'—'}} ms</strong></div></template></section>
        <section v-if="agent.permissions.includes('users.manage')" class="settings-card"><h2>Usuarios <button class="link-button" @click="loadUsers">Actualizar</button></h2><form class="user-form" @submit.prevent="createUser"><label>Nombre<input v-model="userName" required minlength="2"></label><label>Usuario<input v-model="userLogin" required minlength="3"></label><label>Contraseña nueva (mín. 12)<input v-model="userPassword" type="password" required minlength="12" autocomplete="new-password"></label><label>Rol<select v-model="userRole"><option value="AGENT">Agente</option><option value="ADMIN">Admin</option><option value="SUPERADMIN">Superadmin</option></select></label><label>Máximo chats<input v-model.number="userCapacity" type="number" min="1" max="100"></label><button class="primary">Crear usuario</button></form><h3>Equipo</h3><label>Al desactivar, chats activos a<select v-model="deactivateTarget"><option value="QUEUE">Cola general</option><option v-for="u in users.filter(x=>x.active&&x.status==='ONLINE')" :key="u.id" :value="u.id">{{u.name||u.username}} · {{u.active_chat_count}}/{{u.max_active_chats}}</option></select></label><div v-for="u in users" :key="u.id" class="status-row"><span>{{u.name||u.username}} · {{u.role}} · {{u.status}} · {{u.active_chat_count}}/{{u.max_active_chats}}</span><button v-if="u.active&&u.id!==agent.id" class="link-button" @click="deactivateUser(u)">Desactivar</button></div></section>
      </div>
      </main></div>
   <div v-else-if="page==='inbox'||page==='archive'" class="workspace">
     <aside class="inbox"><div class="inbox-head"><div class="eyebrow">BANDEJA DE ASESORES</div><div class="heading-row"><h2>{{filter==='closed'?'Archivo':'Conversaciones'}}</h2><span class="count">{{items.length}}</span></div><div class="search"><Search :size="17"/><input v-model="search" aria-label="Buscar conversaciones" placeholder="Buscar por nombre, teléfono o ID" @input="scheduleSearch"></div></div><div class="filters"><button v-for="[id,label] in filters.filter(f=>page==='archive'?f[0]==='closed':f[0]!=='closed')" :key="id" :class="['filter',filter===id?'active':'']" @click="filter=id;changeFilter()">{{label}}</button></div><div class="conversation-list"><button v-for="item in items" :key="item.id" :class="['conversation-item',selected?.id===item.id?'selected':'']" @click="choose(item)"><div class="avatar">{{initial(item.name)}}</div><div class="conversation-copy"><div class="conversation-title"><strong>{{item.name||item.phone||'Contacto'}}</strong><time>{{when(item.last_message_at)}}</time></div><p>{{item.last_text||'Sin texto'}}</p><div class="conversation-meta"><span :class="['mode-badge',item.mode.toLowerCase()]">{{modeLabels[item.mode]}}</span><span v-if="item.unread_count" class="unread">{{item.unread_count}}</span></div></div></button><div v-if="!items.length" class="empty-list">No hay conversaciones para este filtro.</div><button v-if="nextCursor" class="outline wide" @click="loadList(true)">Cargar más conversaciones</button></div><div class="inbox-foot"><span class="live-dot"></span> Mensajes sincronizados en vivo</div></aside>
     <main v-if="selected" class="chat"><div class="chat-header"><div class="avatar medium">{{initial(selected.name)}}</div><div><h2>{{selected.name||selected.phone||'Contacto'}}</h2><small>WhatsApp · {{selected.phone||'Número no disponible'}}</small></div><span :class="['mode-badge',selected.mode.toLowerCase()]">{{modeLabels[selected.mode]}}</span></div>
      <div class="chat-tags"><span v-for="tag in conversationTags" :key="tag.id" class="tag-chip" :style="{borderColor:tag.color}">{{tag.name}}</span><select v-if="canSend" v-model="tagToAdd" aria-label="Agregar tag"><option value="">+ Tag</option><option v-for="tag in tagOptions.filter(t=>!conversationTags.some(c=>c.id===t.id))" :key="tag.id" :value="tag.id">{{tag.name}}</option></select><button v-if="canSend&&tagToAdd" class="link-button" @click="addTag">Agregar</button></div>
       <div ref="chatScroll" class="message-list" @scroll="onChatScroll"><button v-if="hasOlder" class="link-button" :disabled="olderBusy" @click="loadOlder">Cargar mensajes anteriores</button><div v-if="selected.mode==='CLOSED'" class="closed-banner"><strong>Conversación cerrada</strong><span>{{dispositions.find(x=>x[0]===history.find(h=>h.id===selected?.id)?.disposition)?.[1]||'Historial archivado'}} · {{selected.assigned_to||'Sin agente final'}}</span></div><div v-for="msg in messages" :key="msg.id" :class="['message-row',msg.direction==='outbound'?'outbound':'inbound']"><div class="bubble"><div v-if="msg.sender_type!=='customer'" class="bubble-by">{{msg.sender_type==='human'?'AGENTE':msg.route==='AI'?'IA':'BOT'}}</div><div v-if="displayMessageText(msg)" class="message-text">{{displayMessageText(msg)}}</div>
      <span v-if="msg.direction==='outbound'&&msg.id.startsWith('optimistic:')&&msg.message_type!=='text'" class="muted">Enviando archivo…</span>
      <span v-else-if="msg.direction==='inbound'&&['PENDING','DOWNLOADING','QUEUED'].includes(msg.storage_status||'')&&msg.message_type!=='text'" class="muted">{{msg.message_type==='audio'?'Audio':'Imagen o archivo'}} cargando…</span>
      <span v-else-if="msg.direction==='inbound'&&msg.storage_status==='FAILED'" class="muted">No pudimos cargar este archivo. <button class="link-button" @click="retryIncomingMedia(msg)">Reintentar</button></span>
      <img v-else-if="['image','sticker'].includes(msg.message_type)&&mediaSafe(msg.media_url)" :src="`${mediaSafe(msg.media_url)}?thumbnail=1`" loading="lazy" alt="Imagen compartida" class="media-image" @click="openMedia(msg.media_url)">
      <template v-else-if="msg.message_type==='audio'&&mediaSafe(msg.media_url)"><audio v-if="audioSupported(msg)||msg.playable_available" :src="playable(msg)" controls preload="metadata" @play="($event.target as HTMLAudioElement).playbackRate=audioRate"></audio><span v-if="msg.duration" class="muted">{{Math.round(msg.duration)}} s</span><div class="audio-speeds"><button v-for="rate in [1,1.5,2]" :key="rate" :class="['link-button',audioRate===rate?'active':'']" @click="setAudioRate(rate,$event.currentTarget as HTMLButtonElement)">{{rate}}x</button></div><a v-if="!audioSupported(msg)&&!msg.playable_available" :href="mediaSafe(msg.media_url)" download>Descargar audio (formato no compatible)</a></template>
      <video v-else-if="msg.message_type==='video'&&mediaSafe(msg.media_url)" :src="mediaSafe(msg.media_url)" controls preload="none" class="media-video"></video>
       <a v-else-if="msg.media_url&&mediaSafe(msg.media_url)" :href="mediaSafe(msg.media_url)" target="_blank" rel="noopener noreferrer" download><FileText :size="16"/> {{msg.file_name||msg.message_type}} <span v-if="msg.mime_type">· {{msg.mime_type}}</span><span v-if="msg.media_size"> · {{Math.ceil(msg.media_size/1024)}} KB</span></a>
      <span v-else-if="msg.message_type!=='text'" class="muted">{{msg.message_type}} · archivo no disponible</span>
        <div class="bubble-bottom"><time>{{when(msg.provider_timestamp||msg.created_at)}}</time><span v-if="msg.delivery_status" :class="['delivery',msg.delivery_status]">{{msg.delivery_status==='failed'?'Error de envío':msg.delivery_status}}</span><button v-if="agent?.permissions.includes('audit.view')&&msg.correlation_id" class="link-button" @click="showTrace(msg.id)">Ver trazabilidad</button></div></div></div><div v-if="!messages.length" class="chat-empty">Aún no hay mensajes en esta conversación.</div></div>
        <button v-if="newMessages" class="new-messages" @click="chatScroll?.scrollTo({top:chatScroll.scrollHeight,behavior:'smooth'});newMessages=false">Nuevos mensajes ↓</button><div v-if="canSend" class="composer"><div class="quick-replies" v-if="menu"><button v-for="reply in menu.quickReplies" :key="reply" @click="draft=reply">{{reply}}</button></div><div class="compose-box"><textarea v-model="draft" aria-label="Escribe un mensaje" placeholder="Escribe un mensaje..." rows="1" @keydown.enter.exact.prevent="send"></textarea><label class="attach-button" title="Adjuntar imagen o documento"><Paperclip :size="20"/><input type="file" hidden accept="image/jpeg,image/png,image/webp,image/gif,application/pdf,.doc,.docx,.xls,.xlsx" @change="file=($event.target as HTMLInputElement).files?.[0]||null"></label><button class="primary" :disabled="busy||(!draft.trim()&&!file)" @click="send"><Send :size="16"/> Enviar</button></div><small v-if="file" class="muted">Adjunto: {{file.name}}</small></div><div v-else class="composer muted">{{selected.mode==='HUMAN_PENDING'?'Toma la conversación para responder.':selected.mode==='CLOSING'?'Enviando despedida; conversación visible hasta confirmación.':selected.mode==='CLOSED'?'Conversación archivada.':'No puedes responder en este estado.'}}</div>
    </main>
    <main v-else class="chat welcome-pane"><div class="welcome-art">✦</div><h2>Todo en un solo lugar</h2><p>Selecciona una conversación para empezar a atenderla.</p></main>
     <aside v-if="selected" class="details"><div class="details-title">CONTACTO</div><div class="contact-card"><div class="avatar large">{{initial(selected.name)}}</div><h2>{{selected.name||'Sin nombre'}}</h2><span :class="['mode-badge',selected.mode.toLowerCase()]">{{modeLabels[selected.mode]}}</span></div><div class="details-section"><div class="detail"><span>Teléfono</span><strong>{{selected.phone||'No disponible'}}</strong></div><div class="detail"><span>Contact ID</span><strong class="mono">{{selected.provider_contact_id}}</strong></div><div class="detail"><span>Asignado a</span><strong>{{selected.assigned_to||'Sin asignar'}}</strong></div><div class="detail"><span>Último mensaje</span><strong>{{when(selected.last_message_at)}}</strong></div></div><div v-if="sharedLocations.length" class="details-section"><div class="details-title">UBICACIONES</div><div v-for="location in sharedLocations" :key="location.id" class="detail"><span>📍 {{location.latitude}}, {{location.longitude}}</span><a :href="mapLink(location)" target="_blank" rel="noopener noreferrer">Ver mapa ↗</a></div></div><div class="details-section actions"><div class="details-title">ACCIONES</div><button v-if="selected.mode==='HUMAN_PENDING'" class="primary wide" :disabled="busy" @click="action('claim')">Tomar conversación →</button><button v-if="['HUMAN_ACTIVE','HUMAN_PENDING'].includes(selected.mode)&&canTransfer" class="outline wide" :disabled="busy" @click="action('return-to-bot')">↩ Devolver al bot</button><button v-if="canTransfer" class="outline wide" :disabled="busy" @click="openTransfer">Transferir</button><button v-if="canTransfer" class="outline wide" :disabled="busy" @click="closeDialog=true">Cerrar conversación</button><p class="muted small-text">En modo humano no se llama al AI Engine de n8n.</p></div><div class="details-section"><div class="details-title">NOTAS INTERNAS · no se envían por WhatsApp</div><form v-if="canSend" @submit.prevent="addNote"><textarea v-model="noteDraft" maxlength="2000" placeholder="Nota para el equipo" rows="2"></textarea><button class="outline" :disabled="!noteDraft.trim()">Guardar nota</button></form><div v-for="note in notes" :key="note.id" class="internal-note"><strong>{{note.author}}</strong><p>{{note.text}}</p><small>{{note.created_at}}</small></div></div><div class="details-section"><div class="details-title">HISTORIAL DEL CONTACTO</div><button v-for="session in history.filter(x=>x.id!==selected?.id)" :key="session.id" class="history-item" @click="openHistory(session.id)"><strong>{{session.disposition||session.mode}}</strong><small>{{session.created_at}} · {{session.assigned_to||'Sin agente'}}</small></button></div></aside>
   </div>
      <div v-if="selectedUser" class="modal-overlay" @click.self="selectedUser=null"><div class="action-modal" role="dialog" aria-modal="true" aria-label="Detalle de usuario"><h2>{{selectedUser.name||selectedUser.username}}</h2><div class="status-row"><span>Usuario</span><strong>{{selectedUser.username}}</strong></div><div class="status-row"><span>Rol</span><strong>{{selectedUser.role}}</strong></div><div class="status-row"><span>Estado</span><strong>{{selectedUser.status}}</strong></div><div class="status-row"><span>Chats / capacidad</span><strong>{{selectedUser.active_chat_count}} / {{selectedUser.max_active_chats}}</strong></div><label v-if="selectedUser.active&&selectedUser.id!==agent?.id">Al desactivar, chats activos a<select v-model="deactivateTarget"><option value="QUEUE">Cola general</option><option v-for="person in users.filter(u=>u.active&&u.status==='ONLINE'&&u.id!==selectedUser?.id)" :key="person.id" :value="person.id">{{person.name||person.username}}</option></select></label><div class="modal-actions"><button class="outline" @click="selectedUser=null">Cerrar</button><button v-if="selectedUser.active&&selectedUser.id!==agent?.id" class="outline danger" @click="deactivateUser(selectedUser);selectedUser=null">Desactivar</button></div></div></div>
      <div v-if="closeDialog" class="modal-overlay"><form class="action-modal" @submit.prevent="closeChat()"><h2>Cerrar conversación</h2><label>Resultado del chat *<select v-model="disposition" required><option value="" disabled>Selecciona un resultado</option><option v-for="[value,label] in dispositions" :key="value" :value="value">{{label}}</option></select></label><label>Nota opcional<textarea v-model="closeNote" maxlength="1000"></textarea></label><label v-if="disposition==='SALE_COMPLETED'">Monto opcional<input v-model.number="saleAmount" type="number" min="0" step="0.01"></label><label v-if="disposition==='SALE_COMPLETED'">Pedido o factura opcional<input v-model="saleReference" maxlength="100"></label><label v-if="disposition==='FOLLOW_UP'">Fecha de seguimiento opcional<input v-model="followUpAt" type="datetime-local"></label><p v-if="closeError" class="form-error">El mensaje de cierre no pudo confirmarse. Puede haber llegado al cliente: compruébalo antes de actuar.</p><p v-else>Se enviará el mensaje final antes de archivar el chat.</p><button type="button" class="outline" @click="closeDialog=false;closeError=false">Cancelar</button><button class="primary" :disabled="busy||!disposition">{{closeError?'Reintentar cierre':'Cerrar conversación'}}</button><button v-if="closeError&&agent?.permissions.includes('conversation.close_all')" type="button" class="outline" :disabled="busy" @click="closeChat(true)">Cerrar de todas formas</button></form></div>
     <div v-if="transferDialog" class="modal-overlay"><form class="action-modal" @submit.prevent="transferChat"><h2>Transferir conversación</h2><label>Destino<select v-model="transferTarget"><option value="">Cola general</option><option v-for="person in agents.filter(a=>a.id!==agent?.id&&a.status==='ONLINE')" :key="person.id" :value="person.id">{{person.username}} · en línea</option></select></label><label>Motivo (opcional)<textarea v-model="transferReason" maxlength="500"></textarea></label><button type="button" class="outline" @click="transferDialog=false">Cancelar</button><button class="primary" :disabled="busy">Transferir</button></form></div>
     <div v-if="lightbox" class="media-lightbox" role="dialog" aria-label="Imagen ampliada" @click.self="lightbox=''"><div class="media-lightbox-actions"><button @click="zoom=Math.max(1,zoom-.25)">−</button><span>{{Math.round(zoom*100)}}%</span><button @click="zoom=Math.min(4,zoom+.25)">+</button><a :href="lightbox" download>Descargar</a><button @click="lightbox=''">Cerrar ×</button></div><div class="media-lightbox-viewport"><img :src="lightbox" :style="{transform:`scale(${zoom})`}" alt="Imagen ampliada"></div></div>
     <div v-if="messageTrace" class="modal-overlay" @click.self="messageTrace=null"><div class="action-modal trace-modal"><h2>Trazabilidad del mensaje</h2><small>ID {{messageTrace.messageId}} · correlación {{messageTrace.trace.correlation_id}}</small><div class="trace-rows"><div v-for="(value,key) in messageTrace.trace" :key="key" class="status-row"><span>{{key.replaceAll('_',' ')}}</span><strong>{{value??'—'}}</strong></div></div><p>Los timestamps entre proveedor, CAP y navegador dependen de relojes distintos; las duraciones monotónicas son más fiables.</p><button class="outline" @click="messageTrace=null">Cerrar</button></div></div>
   </template>
 </div>
</template>
