<script setup lang="ts">
import { UserRoundPlus, Check } from '@lucide/vue';
defineProps<{view:any}>();
</script>
<template>
 <main class="page-scroll canonical-page" data-parity="page"><div class="page-heading"><div><h1>Equipo y permisos</h1><p>Usuarios, capacidad de atención y control de acceso por rol.</p></div><button v-if="view.canUsers" class="primary page-action" @click="view.newUser"><UserRoundPlus :size="18"/>Nuevo usuario</button></div>
  <section class="card team-table" data-parity="team-table"><div class="team-columns team-heading"><details class="team-search-menu"><summary>Usuario</summary><label>Buscar usuarios<input :value="view.search" @input="view.onSearch" placeholder="Buscar usuarios" aria-label="Buscar usuarios"></label></details><span>Rol</span><span>Estado</span><span>Carga actual</span><span>Capacidad</span><span>Activo</span></div><div v-for="u in view.rows" :key="u.id" class="team-columns team-row" :style="{opacity:u.active?1:.55}"><span class="team-person"><span class="team-avatar">{{u.initials}}</span><span><strong>{{u.name}}</strong><small>@{{u.username}}</small></span></span><span><span class="role-chip" :style="{background:u.roleBg,color:u.roleFg}">{{u.roleLabel}}</span></span><span class="person-status"><i :style="{background:u.dot}"/>{{u.statusLabel}}</span><span class="person-load"><span><i :style="{width:u.loadWidth,background:u.loadColor}"/></span><small>{{u.load}}</small></span><span class="capacity-control"><button aria-label="Menos capacidad" :disabled="!u.canDecrease" @click="u.decrease">−</button><strong>{{u.max_active_chats}}</strong><button aria-label="Más capacidad" :disabled="!u.canIncrease" @click="u.increase">+</button></span><button class="switch-control" :class="{on:u.active}" :aria-label="`Ver estado de ${u.name}`" @click="u.onClick"><span/></button></div></section>
  <div class="role-grid" data-parity="role-counts"><div v-for="r in view.roles" :key="r.role" class="role-card"><strong>{{r.count}}</strong><span><strong>{{r.label}}</strong><small>{{r.permissions}} permisos</small></span></div></div>
  <details class="team-secondary-actions"><summary>Detalles de usuarios</summary><div><button v-for="u in view.rows" :key="u.id" @click="u.onDetail">{{u.name}} · Ver detalle</button></div></details>
  <section class="card permission-card" data-parity="permissions"><div class="permission-columns permission-heading"><div><h3>Permisos por rol</h3><p>Los permisos efectivos se aplican en el servidor.</p></div><span>Asesor</span><span>Admin</span><span>Superadmin</span></div><div v-for="g in view.groups" :key="g.title" class="permission-group"><h4>{{g.title}}</h4><div v-for="p in g.rows" :key="p.id" class="permission-columns permission-row"><span><span>{{p.label}}</span><small v-if="p.desc">{{p.desc}}</small></span><span v-for="r in p.roles" :key="r.role"><button class="permission-box" :class="{checked:r.checked,locked:r.role==='SUPERADMIN'}" disabled :aria-label="`${p.label}: ${r.role}`" :aria-pressed="r.checked"><Check v-if="r.checked" :size="15" :stroke-width="3"/></button></span></div></div></section>
 </main>
</template>
