<script setup lang="ts">
import { UserRound, Clock3, Bot, ListTree, TriangleAlert, CircleCheck } from '@lucide/vue';
import { ref, watch, nextTick } from 'vue';
const props=defineProps<{view:any}>();
const dialog=ref<HTMLFormElement|null>(null);
let previousFocus:HTMLElement|null=null;
watch(()=>props.view.kind,async kind=>{if(kind){previousFocus=document.activeElement as HTMLElement;await nextTick();dialog.value?.focus({preventScroll:true});}else previousFocus?.focus({preventScroll:true});});
function trapFocus(event:KeyboardEvent){const nodes=Array.from(dialog.value?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),select:not(:disabled),summary')||[]).filter(el=>el.getClientRects().length&&!el.classList.contains('sr-only'));const first=nodes[0],last=nodes.at(-1);if(!first)return;if(event.shiftKey&&(document.activeElement===first||document.activeElement===dialog.value)){event.preventDefault();last?.focus();}else if(!event.shiftKey&&(document.activeElement===last||document.activeElement===dialog.value)){event.preventDefault();first.focus();}}
const icons:Record<string,any>={UserRound,Clock3,Bot,ListTree};
</script>
<template>
 <div v-if="view.kind" class="modal-overlay canonical-modal" @click.self="view.close"><form ref="dialog" tabindex="-1" class="action-modal" role="dialog" aria-modal="true" :aria-label="view.kind==='close'?'Finalizar conversación':view.kind==='transfer'?'Transferir conversación':view.kind==='reopen'?'Reabrir conversación':view.kind==='deact'?'Desactivar usuario':'Nuevo usuario'" @keydown.tab="trapFocus" @keydown.esc.prevent="view.close" @submit.prevent="view.kind==='close'?view.closeChat():view.kind==='transfer'?view.transfer():view.kind==='newUser'?view.createUser():view.kind==='deact'?view.deactivate():undefined">
  <template v-if="view.kind==='close'"><div><h2>Finalizar conversación</h2><div class="modal-subtitle">{{view.name}} · elige el resultado para tus métricas</div></div><div class="modal-options"><button v-for="[id,label] in view.dispositions" :key="id" type="button" class="modal-pill" :class="{selected:view.disposition===id}" @click="view.selectDisposition(id)">{{label}}</button></div><select class="sr-only" aria-label="Resultado del chat" :value="view.disposition" @change="view.onDisposition" required><option value="" disabled>Selecciona un resultado</option><option v-for="[id,label] in view.dispositions" :key="id" :value="id">{{label}}</option></select>
   <div v-if="view.disposition==='SALE_COMPLETED'" class="modal-input-grid"><label>Monto (opcional)<input type="number" min="0" step="0.01" :value="view.amount" @input="view.onAmount" placeholder="0,00"></label><label>Pedido o factura<input :value="view.reference" @input="view.onReference" maxlength="100" placeholder="#4471"></label></div><template v-if="view.disposition==='FOLLOW_UP'"><label>Fecha de seguimiento<input type="datetime-local" :value="view.follow" @input="view.onFollow"></label><small class="muted">Aparecerá en la bandeja «Seguimiento» para reabrirla a tiempo.</small></template>
   <label>Nota interna (opcional)<textarea rows="2" :value="view.note" @input="view.onNote" maxlength="1000"/></label><div class="modal-preview"><span>Despedida que recibirá el cliente</span><div>{{view.farewell}}</div><small>Se archiva solo cuando WhatsApp confirma la entrega. El siguiente mensaje del cliente abrirá una sesión nueva.</small></div><p v-if="view.closeError" class="form-error">El mensaje de cierre no pudo confirmarse. Puede haber llegado al cliente: compruébalo antes de actuar.</p><div class="modal-actions"><button type="button" class="outline" @click="view.close">Cancelar</button><button class="primary" aria-label="Cerrar conversación" :disabled="view.busy||!view.disposition">{{view.closeError?'Reintentar cierre':'Finalizar y enviar despedida'}}</button></div><button v-if="view.closeError&&view.canForce" type="button" class="outline" :disabled="view.busy" @click="view.closeChat(true)">Cerrar de todas formas</button>
  </template>
  <template v-else-if="view.kind==='transfer'"><div><h2>Transferir conversación</h2><div class="modal-subtitle">{{view.name}}</div></div><div class="transfer-kinds"><button v-for="k in view.kinds" :key="k.id" type="button" :class="{selected:k.id===view.transferKind}" :disabled="k.disabled" @click="view.setKind(k.id)"><component :is="icons[k.icon]" :size="20"/><strong>{{k.label}}</strong><small>{{k.desc}}</small></button></div><div v-if="view.transferKind==='agent'" class="transfer-people"><button v-for="a in view.transferAgents" :key="a.id" type="button" :class="{selected:a.selected}" :disabled="!a.available" @click="view.selectTarget(a.id)"><span class="transfer-avatar">{{a.initials}}</span><span><strong>{{a.name}}</strong><small><i :style="{background:a.dot}"/>{{a.statusLabel}}<span v-if="!a.available"> · {{a.status==='ONLINE'?'Sin capacidad':a.statusLabel}}</span></small></span><span class="transfer-load"><small>{{a.load}} chats</small><span><i :style="{width:a.loadWidth}"/></span></span></button></div><label>Motivo (opcional, queda en el historial)<textarea rows="2" placeholder="Ej.: requiere precio mayorista" maxlength="500" :value="view.reason" @input="view.onReason" :readonly="view.transferKind==='menu'"/></label><div class="modal-preview"><span>{{view.transferKind==='agent'?'El cliente no recibe aviso. El asesor verá todo el historial, las notas y el motivo.':view.transferKind==='queue'?'Quedará en espera y se asignará al asesor disponible con menos carga.':'El cliente recibirá este mensaje:'}}</span><div v-if="view.transferKind==='menu'">{{view.returnPreview}}</div></div><div class="modal-actions"><button type="button" class="outline" @click="view.close">Cancelar</button><button class="primary" :disabled="view.busy||(view.transferKind==='agent'&&!view.target)">Transferir</button></div>
  </template>
  <template v-else-if="view.kind==='deact'"><div><h2>Desactivar a {{view.deName}}</h2><div class="modal-subtitle">Tiene {{view.deCount}} chats activos. ¿A dónde los enviamos?</div></div><div class="modal-options"><button v-for="t in view.deTargets" :key="t.id" type="button" class="modal-pill" :class="{selected:t.id===view.deTarget}" @click="view.selectDeTarget(t.id)">{{t.label}}</button></div><div class="modal-actions"><button type="button" class="outline" @click="view.close">Cancelar</button><button class="deactivate-button" :disabled="view.busy">Desactivar y reasignar</button></div></template>
  <template v-else-if="view.kind==='reopen'"><div><h2>Reabrir conversación</h2><div class="modal-subtitle">{{view.name}} · {{view.previous}}</div></div><div class="reopen-window" :class="{outside:view.reopenOutside}"><TriangleAlert v-if="view.reopenOutside" :size="18" :stroke-width="2.2"/><CircleCheck v-else :size="18" :stroke-width="2.2"/><span>{{view.reopenWindow}}</span></div><label>Primer mensaje al cliente<textarea rows="3" :value="view.reopenText" readonly/></label><p class="reopen-note">Esta conversación permanece archivada. No se iniciará una sesión nueva desde esta vista.</p><div class="modal-actions"><button type="button" class="outline" @click="view.close">Cancelar</button><button class="primary" disabled>Reabrir y enviar</button></div></template>
  <template v-else-if="view.kind==='newUser'"><h2>Nuevo usuario</h2><div class="modal-input-grid"><label>Nombre<input :value="view.userName" @input="view.onUserName" placeholder="Nombre y apellido" required minlength="2"></label><label>Usuario<input :value="view.userLogin" @input="view.onUserLogin" placeholder="usuario" required minlength="3"></label></div><div class="new-user-role">Rol<div><button v-for="r in view.userRoles" :key="r.role" type="button" :class="{selected:r.role===view.userRole}" @click="view.selectRole(r.role)">{{r.label}}</button></div></div><div class="new-user-capacity"><span>Chats simultáneos máximos</span><div><button type="button" aria-label="Menos" @click="view.changeCapacity(-1)">−</button><strong>{{view.capacity}}</strong><button type="button" aria-label="Más" @click="view.changeCapacity(1)">+</button></div></div><details class="user-credentials"><summary>Contraseña nueva</summary><label>Contraseña nueva (mínimo 12 caracteres)<input type="password" :value="view.userPassword" @input="view.onUserPassword" minlength="12" autocomplete="new-password"></label></details><div class="modal-actions"><button type="button" class="outline" @click="view.close">Cancelar</button><button class="primary" :disabled="view.userName.trim().length<2||view.userLogin.trim().length<3||view.userPassword.length<12">Crear usuario</button></div></template>
 </form></div>
</template>
