<script setup lang="ts">
import { PlugZap, Webhook, Globe, Activity } from '@lucide/vue';
defineProps<{view:any}>();
const icons:Record<string,any>={PlugZap,Webhook,Globe,Activity};
</script>
<template>
 <main class="page-scroll canonical-page" data-parity="page"><div class="page-heading"><div><h1>Configuración</h1><p>Solo ajustes que cambian cómo se atiende. Los cambios se guardan al instante.</p></div></div><div class="segmented settings-tabs"><button v-for="t in view.tabs" :key="t.id" :class="{selected:t.selected}" @click="t.onClick">{{t.label}}</button></div>
  <div v-if="view.section==='routing'||view.section==='ai'" class="settings-columns" data-parity="settings-columns"><section class="settings-controls"><div v-for="t in view.toggles" :key="t.label" class="settings-control-row"><div><strong>{{t.label}}</strong><p>{{t.help}}</p></div><button class="switch-control" :class="{on:t.value===true}" disabled :aria-label="t.label" title="Configuración administrada en el servidor"><span/></button></div><p v-if="view.section==='ai'" class="ai-settings-note">Solo el texto libre en modo IA llama a n8n. Menú, respuestas fijas, media y chats humanos nunca consumen IA.</p></section><section class="settings-controls"><div v-for="n in view.numbers" :key="n.label" class="settings-control-row"><div><strong>{{n.label}}</strong><p>{{n.help}}</p></div><div class="number-control"><button aria-label="Menos" disabled>−</button><strong>{{n.value??'—'}}</strong><button aria-label="Más" disabled>+</button></div></div></section></div>
  <section v-else-if="view.section==='dispositions'" class="disposition-settings" data-parity="dispositions"><div v-for="d in view.dispositions" :key="d.id" class="disposition-setting-row"><div><strong>{{d.label}}</strong><small>{{d.id}}</small></div><div><button class="need-pill" :class="{selected:d.amount}" disabled>Pide monto</button><button class="need-pill" :class="{selected:d.follow}" disabled>Pide fecha</button></div><button class="switch-control on" disabled aria-label="Activar tipificación"><span/></button></div><div class="disposition-new"><input placeholder="Nueva tipificación, p. ej. «Garantía»" disabled><button disabled>Añadir</button></div><p>Las inactivas no aparecen al finalizar chats, pero se conservan en métricas históricas.</p></section>
  <div v-else-if="view.section==='whatsapp'" class="whatsapp-settings" data-parity="whatsapp"><div class="whatsapp-cards"><article v-for="w in view.waCards" :key="w.label"><component :is="icons[w.icon]" :size="22"/><span>{{w.label}}</span><strong>{{w.value}}</strong></article></div><section class="settings-controls"><div v-for="t in view.waToggles" :key="t.label" class="settings-control-row"><div><strong>{{t.label}}</strong><p>{{t.help}}</p></div><button class="switch-control" disabled :aria-label="t.label"><span/></button></div><div class="whatsapp-test"><span>Las credenciales y el secreto del webhook nunca se muestran en la interfaz.</span><button @click="view.testConnection">Probar conexión</button></div></section></div>
 </main>
</template>
